### ISSUE TITLE
Using Toolkit and ILMerge

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#1066]
<b>joshglass1[CodePlex]</b> <br />I am trying to merge Xceed.Wpf.Toolkit.dll to a simple exe file. Everything that I do is failing. I am trying to run the tool from the command line. I have tried the following:

ilmerge /targetplatform:v4,quot%ProgramFiles%\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0quot quotC:\Program Files (x86)\Microsoft\ILMerge\myproject.exequot quotC:\Program Files (x86)\Microsoft\ILMerge\Xceed.Wpf.Toolkit.dllquot /closed
 /out:quotC:\Users\MyName\Desktop\PlaceEXEHere\MergedFile.exequot /target:winexe /ndebug ---- this gives error ERROR!!: Duplicate type 'XamlGeneratedNamespace.GeneratedInternalTypeHelper' found in assembly 'Xceed.Wpf.Toolkit'

Then I tried

ilmerge /targetplatform:v4,quot%ProgramFiles%\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0quot quotC:\Program Files (x86)\Microsoft\ILMerge\myproject.exequot quotC:\Program Files (x86)\Microsoft\ILMerge\Xceed.Wpf.Toolkit.dllquot /closed
 /union /out:quotC:\Users\MyName\Desktop\PlaceEXEHere\MergedFile.exequot /target:winexe /ndebug ---- this gives error The assembly 'Xceed.Wpf.Toolkit' was not merged in correctly

what am I doing wrong? Any suggestions? Thanks in advance

**Comment by Suplanus** [comment]
Its not a Xceed problem, its a problem how WPF creates the types. See [here](https://roman.st/Article/ILMerge-and-GeneratedInternalTypeHelper).
