### ISSUE TITLE
Enhancement: CheckComboBox Text/Visual when nothing is selected

### ISSUE THREAD

**Issue by TWhidden** [xceedsoftware/wpftoolkit#1152]
Gauging Interest...

Having a watermark option such for the developer to leave a visual cue or text message in the ComboBox such as "SELECT FILTERS", when no items are selected. 

I couldn't seem to find that in the docs, so I suspect that isn't currently supported.  I was thinking about adding it on a branch. Question is, would that be something of interest for others? Please correct me if I am wrong. I did test the 'Text' property, but that is more about formatting according to the docs.

The idea would give visual cues to users, instead of having to place a TextBlock next to it with something like "SELECT HERE".  Saves some layout room. The "Content" would accept any element so you could put text or a visual object in.

**Comment by XceedBoucherS** [comment]
Hi,

The Toolkit already includes a WatermarkComboBox. 
You can try it in the LiveExplorer.
Thanks.

**Comment by RichardD2** [comment]
I also need a visual cue or text message for the `CheckComboBox` when no items are selected.

Suggesting a completely different control, with totally different behaviour, is **NOT** a solution.

**Comment by XceedBoucherS** [comment]
Hi RichardD2,
Sorry about that, I thought you were talking about a ComboBox and needed a Watermark.
If you take a look at v4.4 of the Toolkit (currently available for commercial users at https://xceed.com/en/our-products/product/toolkit-plus-for-wpf, but soon available to GitHub users ), you will see that we added a 
AllItemsSelectedContent for the CheckComboBox.
We could easily add a NoItemSelectedContent (or Watermark) property.

Thank you for your suggestion.
