### ISSUE TITLE
AvalonDock: Problem hiding/showing panes after saving and reloading layout

### ISSUE THREAD

**Issue by cmkessell** [xceedsoftware/wpftoolkit#1153]
Hi,

I've encountered a problem with AvalonDock v3.10.  The commercial v3.4 release also exhibits the same behaviour. (I submitted this question on the Xceed forum last week but had no response there.)

I've found that the hiding and re-displaying of panes no longer seems to work correctly after a layout has been saved and re-loaded using XmlLayoutSerializer.  I’ve created a bare minimum WPF project that displays the problem:

XAML:

<Window x:Class="AvalonDockTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:xcad="http://schemas.xceed.com/wpf/xaml/avalondock"
        xmlns:local="clr-namespace:AvalonDockTest"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">

    <DockPanel>
        <StackPanel DockPanel.Dock="Top" Orientation="Horizontal">
            <Button Content="Save Layout" Click="SaveLayout_Click" Margin="5"/>
            <Button Content="Load Layout" Click="LoadLayout_Click" Margin="5"/>
            <Button Content="Hide Pane 1" Click="HidePane1_Click" Margin="5"/>
            <Button Content="Show Pane 1" Click="ShowPane1_Click" Margin="5"/>
            <Button Content="Hide Pane 2" Click="HidePane2_Click" Margin="5"/>
            <Button Content="Show Pane 2" Click="ShowPane2_Click" Margin="5"/>
        </StackPanel>

        <xcad:DockingManager x:Name="dockingManager">
            <xcad:LayoutRoot>
                <xcad:LayoutPanel Orientation="Horizontal">
                    <xcad:LayoutAnchorablePane>
                        <xcad:LayoutAnchorable x:Name="Pane1" ContentId="Pane1" Title="Pane 1"/>
                    </xcad:LayoutAnchorablePane>
                    <xcad:LayoutAnchorablePane>
                        <xcad:LayoutAnchorable x:Name="Pane2" ContentId="Pane2" Title="Pane 2"/>
                    </xcad:LayoutAnchorablePane>
                </xcad:LayoutPanel>
            </xcad:LayoutRoot>
        </xcad:DockingManager>
    </DockPanel>
</Window>

Code behind:

using System.Windows;
using System.IO;
using Xceed.Wpf.AvalonDock.Layout.Serialization;

namespace AvalonDockTest
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void SaveLayout_Click(object sender, RoutedEventArgs e)
        {
            var serializer = new XmlLayoutSerializer(dockingManager);
            using (var writer = new StreamWriter("avalonlayout.xml"))
                serializer.Serialize(writer);
        }

        private void LoadLayout_Click(object sender, RoutedEventArgs e)
        {
            var serializer = new XmlLayoutSerializer(dockingManager);
            using (var reader = new StreamReader("avalonlayout.xml"))
                serializer.Deserialize(reader);
        }

        private void HidePane1_Click(object sender, RoutedEventArgs e)
        {
            Pane1.Hide();
        }

        private void ShowPane1_Click(object sender, RoutedEventArgs e)
        {
            Pane1.Show();
        }

        private void HidePane2_Click(object sender, RoutedEventArgs e)
        {
            Pane2.Hide();
        }

        private void ShowPane2_Click(object sender, RoutedEventArgs e)
        {
            Pane2.Show();
        }

    }
}

When run this generates a window with some buttons and two docking panes. The buttons allow the panes to be displayed or hidden, and these work fine when the program first runs. However, after the layout has been saved and reloaded using the Save Layout and Load Layout buttons the ability to hide and show panes no longer works.

**Comment by XceedBoucherS** [comment]
Hi,

When deserializing (reloading), AvalonDock will use the new LayoutRoot that was saved. This LayoutRoot doesn't include the "x:Name", so you should avoid using it.
Instead, find the LayoutAnchorable you want by looking at his ContentId :

` var pane2 = dockingManager.Layout.Descendents().OfType< LayoutAnchorable >().Where( x => x.ContentId == "Pane2" ).FirstOrDefault();
     
 if( pane2 != null )
{
       pane2.Show();
}`

**Comment by cmkessell** [comment]
Many thanks for the explanation, I didn't realise that my "x:Name" settings would be removed by the serializer/deserializer.  Your suggested code works perfectly!
