### ISSUE TITLE
AvalonDock  document content ZIndex issue and unpin location isse

### ISSUE THREAD

**Issue by heyixiaoran** [xceedsoftware/wpftoolkit#1154]
In my Demo.  (NuGet 3.4 wpf.avalondock)

1. I add a WebBrowser in the LayoutDocument . Then  pin the bottom tab. The WebBrowser is on the bottom tab  when you make bottom tab size up. 

2. Unpin left side .It will go to the right side. 
    Unpin top side . It will go to the bottom side.

If they are not issues. How to modify my code? Thanks.

[RibbonAndDocker.zip](https://github.com/xceedsoftware/wpftoolkit/files/1168690/RibbonAndDocker.zip)

**Comment by XceedBoucherS** [comment]
Hi,

This is already fixed. The fix will be included in v3.5.
In the meantime, go in file Xceed.Wpf.AvalonDock/Layout/Extentions.cs, and replace the content of the method "GetSide" with :

 var parentContainer = element.Parent as ILayoutOrientableGroup;
      if( parentContainer != null )
      {
        var layoutPanel = parentContainer as LayoutPanel;
        if( layoutPanel == null )
        {
          layoutPanel = parentContainer.FindParent<LayoutPanel>();
        }

        if( (layoutPanel != null) && ( layoutPanel.Children.Count > 0 ) )
        {
          if( layoutPanel.Orientation == System.Windows.Controls.Orientation.Horizontal )
            return ( layoutPanel.Children[ 0 ].Equals(element) || layoutPanel.Children[ 0 ].Descendents().Contains( element ) ) ? AnchorSide.Left : AnchorSide.Right;
          return ( layoutPanel.Children[ 0 ].Equals( element ) || layoutPanel.Children[ 0 ].Descendents().Contains( element ) ) ? AnchorSide.Top : AnchorSide.Bottom;
        }
      }

      Debug.Fail( "Unable to find the side for an element, possible layout problem!" );
      return AnchorSide.Right;

**Comment by heyixiaoran** [comment]
@XceedBoucherS  
Hi 
I found the code is V3.1.  Where is V3.4 code ?
This code which you provide should can fix second issue.  About first  WebBrowser issue how to fix it?

**Comment by XceedBoucherS** [comment]
Currently, the free version available on Nuget is v3.1 and the Plus Edition is at v3.4.
Soon, the free version will be upgraded to v3.2 while the Plus edition will be upgraded to v3.5.
Nuget include the dlls of the free v3.1 version and the dlls of the Plus edition v3.4 ( for 45 days ).

Sorry if I missed the first issue.
You say the Web browser appears in the bottom tab when resizing it up ? From what I see the bottom tab is not being drawn over the WebBrowser. This could be a limitation of WPF : https://stackoverflow.com/questions/9039593/how-can-i-put-webbrowser-display-behind-my-control?lq=1
https://stackoverflow.com/questions/8405697/wpf-z-index-issue

**Comment by heyixiaoran** [comment]
@XceedBoucherS 
AvalonDock 2.0 is correct .So I think it is a regression
