### ISSUE TITLE
Feature Request: Need a property to Lock Layout.

### ISSUE THREAD

**Issue by pegasussanjay** [xceedsoftware/wpftoolkit#1155]
Need  a property to lock the layout to dock/undock/close/hide/resize any LayoutItem.

**Comment by XceedBoucherS** [comment]
Will be available in v3.5.

**Comment by h0st1le** [comment]
What is the name of this property?

**Comment by XceedBoucherS** [comment]
How about:
-CanClose
-CanFloat
-CanHide
-CanAutoHide
-CanMove
