### ISSUE TITLE
Different themes loaded on Windows 7 and Windows 10

### ISSUE THREAD

**Issue by ucahajw** [xceedsoftware/wpftoolkit#1160]
I have developed an application on my Windows 7 machine and edited some of the generic.xaml files to customise the behaviour of some controls.
However, when I deploy on a Windows 10 machine (in fact a virtual machine on my development machine) the themes used are the corresponding aero2.normalcolor.xaml files instead.
Is there any way  I can force the application to use generic.xaml regardless of operating system?

**Comment by XceedBoucherS** [comment]
Hi,
By default, when using Windows 8 and up, its the Aero2.normalColor.xaml that is loaded, while Generic.xaml will be loaded for other operating systems.
You could copy your xaml from Aero2.normalColor.xaml to Generic.xaml so the same stuff will be loaded on all operating systems.

You can also go in file Xceed.Wpf.Toolkit/Themes/Aero2.NormalColor.xaml and replace the paths you wish to point to the generic.xaml files.
