### ISSUE TITLE
"CurrentPage" not binding correctly?

### ISSUE THREAD

**Issue by LGFN** [xceedsoftware/wpftoolkit#1162]
I'm not sure if I'm not using this correctly or it's a bug. Regardless I couldn't find any help on the web.

In XAML:

><xctk:Wizard FinishButtonVisibility="Collapsed" HelpButtonVisibility="Collapsed"
>             CurrentPage="{Binding CurrentStep}" >
>...
></xctk:Wizard>

In C#: 
>public WizardPage CurrentStep { get; set; }

I'd assume that when I navigate from one page to another it'll update reflecting the current page, however all I get is a blank stare and a careless `null`.

Is it a bug, if not what am I doing wrong, and how can I get the current page using MVVM?

**Comment by XceedBoucherS** [comment]
Hi,

You have to make sure the DataContext of the Wizard is properly set. Also that your CurrentStep property is raising a property changed. Here's an example (maybe not MVVM), but you will get the idea :
 <Window.Resources>
    <xctk:WizardPage x:Key="Page0"
                     Title="Welcome to my Wizard"
                     Description="This Wizard will walk you though how to do something." />
    <xctk:WizardPage x:Key="Page1"
                     PageType="Interior"
                     Title="Page 1"
                     Description="This is the first page in the process." />
    <xctk:WizardPage x:Key="Page2"
                     PageType="Interior"
                     Title="Page 2"
                     Description="This is the second page in the process" />
    <xctk:WizardPage x:Key="Page3"
                     PageType="Interior"
                     Title="Last Page"
                     Description="This is the last page in the process"
                     CanFinish="True" />
  </Window.Resources>
    <StackPanel>
      <xctk:Wizard FinishButtonVisibility="Collapsed"
                   HelpButtonVisibility="Collapsed"
                   CurrentPage="{Binding CurrentStep}"
                   DataContext="{Binding}">
      </xctk:Wizard>
    <Button Content="Change Page"
            Click="Button_Click" />
  </StackPanel>

   public MainWindow()
    {
      InitializeComponent();
      this.DataContext = this;
      this.CurrentStep = this.Resources[ "Page2" ] as WizardPage;
    }

    public WizardPage CurrentStep
    {
      get
      {
        return _currentStep;
      }
      set
      {
        _currentStep = value;
        OnPropertyChanged( "CurrentStep" );
      }
    }
    private WizardPage _currentStep;

    private void Button_Click( object sender, RoutedEventArgs e )
    {
      this.CurrentStep = this.Resources[ "Page0" ] as WizardPage;
    }

    public event PropertyChangedEventHandler PropertyChanged;
    protected void OnPropertyChanged( string propertyName )
    {
      if( PropertyChanged != null )
      {
        PropertyChanged( this, new PropertyChangedEventArgs( propertyName ) );
      }
    }

**Comment by LGFN** [comment]
Thanks for your response. However, all other properties in this window work flawlessly, DataContext is set up appropriately. Problem is only with this, when putting breakpoints on its getter and setter it doesn't even hit it at all.

**Comment by XceedBoucherS** [comment]
Hi,

Can you submit a complete sample so I could test ?
If you paste my preceding sample in a new project, it will work.
Thanks.

**Comment by LGFN** [comment]
Ok, I figured out the issue, I needed to add `Mode=TwoWay` to the `CurrentPage` property.
