### ISSUE TITLE
ColorPicker / ColorCanvas: Make Background configurable

### ISSUE THREAD

**Issue by robertmuehsig** [xceedsoftware/wpftoolkit#1164]
It would be nice if we could set the background color for those controls:

![image](https://user-images.githubusercontent.com/756703/29178749-c323335a-7df2-11e7-96a0-fb37c6decc63.png)

Battleship-Grey is not really sexy anymore :)

If you need help and accept PRs please let me know.

**Comment by XceedBoucherS** [comment]
Dupplicate of https://github.com/xceedsoftware/wpftoolkit/issues/1163
