### ISSUE TITLE
RichTextBoxFormatBar appearing outside of parent RichTextBox

### ISSUE THREAD

**Issue by SmithsonianDSP** [xceedsoftware/wpftoolkit#1165]
It is possible to cause the RTF Format Bar to appear outside the bounds of the parent RTF TextBox control 
in certain scenarios.

To reproduce:

1. Create RichTextBox control
2. Add multiple lines of text to the textbox (enough to require scrolling up/down to view entire contents)
3. Click to begin selecting text, hold button down, and drag either all the way up or down, and release the mouse button once cursor is well outside of the textbox control.

&nbsp;

Upon review of the [RtfFormatBarManager.cs](https://github.com/xceedsoftware/wpftoolkit/blob/master/ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/RichTextBoxFormatBar/RichTextBoxFormatBarManager.cs#L199) source, I believe the problem lies in the `PositionFormatBar` method; this method does not check bottom or left boundaries, and the method used for the top and right boundaries does not guarantee that the `top` and/or `left` offsets will result in positive values that are within the bounds of the parent RichTextBox control.

&nbsp;

I have implemented a variation of the `RtfFormatBarManager` with a modified `PositionFormatBar` method that seems to properly prevent this issue; I'll submit it as a PR and let you decide if my solution was satisfactory and merge it or if you'd rather implement your own solution.

**Comment by XceedBoucherS** [comment]
Hi,
The pull request has been merged.
