### ISSUE TITLE
Additional support needed of enum DateTimeFormat

### ISSUE THREAD

**Issue by HansSolos** [xceedsoftware/wpftoolkit#1175]
The DateTimeFormat supports LongDate, LongTime, ShortDate, ShortTime, .. , .. and FullDateTime.
FullDateTime is the combination of LongDate and LongTime.

What I really want, is a format of ShortDate and ShortTime. Something like ShortDateTime.
See attached image for a visual example. I want to have '25/08/2017 09:08' without using Custom format.

![capture](https://user-images.githubusercontent.com/31303691/29703410-c6be2824-8975-11e7-9abf-214614c89eaf.PNG)

**Comment by XceedBoucherS** [comment]
Hi,

The enum is based on the properties from System.Globalization.DateTimeFormatInfo. Unfortunately, this class doesn't include a ShortDate+ShortTime pattern. 
According to this page : https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings, what you want is the "General date/time pattern (short time)" or "g".
You can use the DateTimePicker.Format = "DateTimeFormat.Custom" and the FormatString = "g" and you will have what you want.
