### ISSUE TITLE
How to resize the description area in PropertyGrid

### ISSUE THREAD

**Issue by Maedman** [xceedsoftware/wpftoolkit#1198]
Hi, 

I am using wpftoolkit and specifically the PropertyGrid. I would like set the size of the description area so it has a fixed height. Is there a way to do this?

Thanks
Mark

**Comment by XceedBoucherS** [comment]
Hi,

You will have to modify the PropertyGrid template. 
You can do it in file :
-Xceed.Wpf.Toolkit/PropertyGrid/Themes/Aero2.NormalColor.xaml (for Windows 8 and up)
-Xceed.Wpf.Toolkit/PropertyGrid/Themes/Generic.xaml ( for other Windows )
In the style targeting :
TargetType="{x:Type pg:PropertyGrid}"
Look for the "Template" and adjust the last RowDefinition Height of the first Grid to the wanted value..

**Comment by Maedman** [comment]
Great. Thanks very much!





*From:* XceedBoucherS [mailto:notifications@github.com]
*Sent:* Wednesday, October 04, 2017 8:29 AM
*To:* xceedsoftware/wpftoolkit
*Cc:* Maedman; Author
*Subject:* Re: [xceedsoftware/wpftoolkit] How to resize the description
area in PropertyGrid (#1198)



Hi,

You will have to modify the PropertyGrid template.
You can do it in file :
-Xceed.Wpf.Toolkit/PropertyGrid/Themes/Aero2.NormalColor.xaml (for Windows
8 and up)
-Xceed.Wpf.Toolkit/PropertyGrid/Themes/Generic.xaml ( for other Windows )
In the style targeting :
TargetType="{x:Type pg:PropertyGrid}"
Look for the "Template" and adjust the last RowDefinition Height of the
first Grid to the wanted value..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xceedsoftware/wpftoolkit/issues/1198#issuecomment-334139360>,
or mute the thread
