### ISSUE TITLE
ShowAdvancedButton property missing from ColorPicker

### ISSUE THREAD

**Issue by mrbeck02** [xceedsoftware/wpftoolkit#1199]
I'm currently using the ColorPicker control and it's really nice.  The issue is that after upgrading to 3.2.0.0, the ShowAdvancedButton property is missing.  I thought that maybe the functionality had been moved into another property, but I can't find it.  I'm pretty confused since the AdvancedButtonHeader property is still in the code.  Why have this property and no advanced button?

Please let me know if this feature is being removed or if this is a bug and will be fixed soon.

Thanks,
Matt

**Comment by mrbeck02** [comment]
Is this wrapped up in ShowTabHeaders?

**Comment by XceedBoucherS** [comment]
Hi,

In the ColorPicker from v3.2, the button to switch from standard to advanced view has been changed for tabs. You can find it in the Release notes here : https://xceed.com/release-notes/#toolkit-wpf-3.2.16567.21060 . The last one says : "In ColorPicker, tabs are now used to switch from “standard” to “advanced” view."

The properties AdvancedButtonHeader and StandardButtonHeader remains while ShowAdvancedButton has been renamed to ShowTabHeaders.

In v3.6, the properties AdvancedButtonHeader and StandardButtonHeader will be renamed AdvancedTabHeader and StandardTabHeader to be consistent.

**Comment by BOBJohnson** [comment]
I ran into this today. The current wiki (https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker) still shows "ShowAdvancedButton" and doesn't show the "ShowTabHeaders" property.

**Comment by XceedBoucherS** [comment]
Hi,
The page has been updated.
Thank you for reporting this.
