### ISSUE TITLE
Correct Handling of Anchorable Items

### ISSUE THREAD

**Issue by madenaras** [xceedsoftware/wpftoolkit#1201]
If we have a layout without any LayoutDocumentPane, all of the anchorables are Auto-Hidden on the right side.

Just changing the checks at Layout/Extensions.cs, line 97 to               
` if (!parentContainer.ContainsChildOfType<LayoutDocumentPaneGroup, LayoutDocumentPane>() &&                     !parentContainer.ContainsChildOfType<LayoutAnchorablePaneGroup, LayoutAnchorablePane>())`

and at line 109 to
```
if (childElementAsContainer != null &&                        (childElementAsContainer.IsOfType<LayoutDocumentPane, LayoutDocumentPaneGroup>() ||
                        childElementAsContainer.ContainsChildOfType<LayoutDocumentPane, LayoutDocumentPaneGroup>() ||                        childElementAsContainer.IsOfType<LayoutAnchorablePane, LayoutAnchorablePaneGroup>() ||
                        childElementAsContainer.ContainsChildOfType<LayoutAnchorablePane, LayoutAnchorablePaneGroup>()))
```

will do the trick.

**Comment by XceedBoucherS** [comment]
Hi,

This is already fixed in v3.5. 
You can get it here : https://xceed.com/xceed-toolkit-plus-for-wpf/
