### ISSUE TITLE
Consistent look of docked items

### ISSUE THREAD

**Issue by DWAK-ATTK** [xceedsoftware/wpftoolkit#1205]
Hello.

I've noticed that sometimes the right or left docked items (like "Properties", "Alarms" and "Journal" in the AvalonDock sample xaml) sometimes appear as buttons and sometimes as tabs.  How can I control this?  I like the look of the tabs and would like to see them always instead of the buttons.  How can I achieve that?

Thanks.

**Comment by XceedBoucherS** [comment]
Hi,

What do you mean "sometimes the right or left docked items appear as buttons and sometimes as tabs".
Is this happening in the AvalonDock sample of the LiveExplorer ? If yes, how do you reproduce it ? 
Can you show an image of the 2 situations ?
Thanks.

**Comment by DWAK-ATTK** [comment]
Thanks for responding.
Here is a screenshot to illustrate.

I have not figured out how to reproduce the effect yet.

**Comment by XceedBoucherS** [comment]
Hi,
Thanks for the image.
I understand.
You are testing this in the LiveExplorer of the Toolkit, in the Theming/AvalonDock Controls sample.
When using the "Generic" theme, you should see buttons. 
When using the "Metro" theme, you should see tabs.
When you switch from one theme to another, I believe the Anchored "Tabs" or "Buttons" are not properly refreshed. 
This should not happen if you are using a single theme in your application.
I will try to update the sample.
