### ISSUE TITLE
Exception when PropertyGrid contains System.Drawing.Color in version 3.2

### ISSUE THREAD

**Issue by cwenger** [xceedsoftware/wpftoolkit#1207]
Starting with version 3.2, I get an exception when I try to display a `PropertyGrid` that contains a variable of type `System.Drawing.Color`:

```
System.Reflection.TargetInvocationException occurred
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=<Cannot evaluate the exception source>
Inner Exception 1:
FileNotFoundException: Could not resolve assembly 'System.Drawing.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

For example, I have a `MainWindow` with a button that open a new `ConfigurationWindow` that contains a `PropertyGrid` named `ThePropertyGrid`. Here is the pertinent code:

```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            ConfigurationWindow c = new ConfigurationWindow();
            c.Show();
        }
    }

    public partial class ConfigurationWindow : Window
    {
        public ConfigurationWindow()
        {
            InitializeComponent();

            PropertyGrid.SelectedObject = new Configuration();
        }
    }

    public class Configuration
    {
        public System.Drawing.Color Color { get; set; }
    }
```

I get the exception on `c.Show()`. If I change the type of `Color` from `System.Drawing.Color` to `System.Windows.Media.Color`, it works fine. And again, this worked fine until version 3.2.

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v3.3.

In the meantime, you can go in file Xceed.Wpf.Toolkit/PropertyGrid/Implementation/DescriptorPropertyDefinition.cs,
In method :
CreateAttributeEditor()

and
1) add at the beginning the variable
  Type type = null;

2) Replace the line :
var type = Type.GetType( editorAttribute.EditorTypeName, ( name ) => { return AppDomain.CurrentDomain.GetAssemblies().Where( l => l.FullName == name.FullName ).FirstOrDefault(); }, null, true );
with:
  try
        {
          //# case 166456 : Manage editor located in other assembly
          type = Type.GetType( editorAttribute.EditorTypeName, ( name ) =>
          {
            return AppDomain.CurrentDomain.GetAssemblies().Where( l => l.FullName == name.FullName ).FirstOrDefault();
          }
          , null, true );
        }
        catch( Exception e )
        {
          type = Type.GetType( editorAttribute.EditorTypeName );
        }
