### ISSUE TITLE
Multi-line string in PropertyGrid, how to do this?

### ISSUE THREAD

**Issue by jliliamen** [xceedsoftware/wpftoolkit#1211]
Multi-line string in PropertyGrid, how to do this?

**Comment by XceedBoucherS** [comment]
Hi,

Try to define your own editor : a TextBox which wrap its text :

 <xctk:PropertyGrid x:Name="_PropertyGrid"
                       SelectedObject="{Binding MyPerson}"
                       Width="400">
      <xctk:PropertyGrid.EditorDefinitions>
        <xctk:EditorTemplateDefinition TargetProperties="{x:Type sys:String}">
          <xctk:EditorTemplateDefinition.EditingTemplate>
            <DataTemplate>
              <TextBox Text="{Binding Value}"
                       TextWrapping="Wrap"/>
            </DataTemplate>
          </xctk:EditorTemplateDefinition.EditingTemplate>
        </xctk:EditorTemplateDefinition>
      </xctk:PropertyGrid.EditorDefinitions>
    </xctk:PropertyGrid>

**Comment by jliliamen** [comment]
Is there a way to do this (adding some sort of attribute) in the bound object class as opposed to changing my xaml?

**Comment by jliliamen** [comment]
@XceedBoucherS : I'm sorry but your code sample doesn't seem to work or I may be getting something wrong: 
![image](https://user-images.githubusercontent.com/16106587/36065724-9fb5c35a-0e53-11e8-9053-94ab80dd59cc.png)

**Comment by XceedBoucherS** [comment]
dupplicate of https://github.com/xceedsoftware/wpftoolkit/issues/1264
