### ISSUE TITLE
Legacy MaskedTextBox

### ISSUE THREAD

**Issue by MrQ99** [xceedsoftware/wpftoolkit#1218]
Having recently updated to v3.2 we've just noticed that all uses of the MaskedTextBox no longer operate as before and as currently coded and we need to revert to the obsolete version ASAP.

We currently use as follows:

xmlns:xctk="http://schemas.xceed.com/wpf/xaml/toolkit"
<xctk:MaskedTextBox ....etc />

Please advise how we should resort to using obsolete version from the Xceed.Wpf.Toolkit.Obselete namespace, until we have time to move forward to use the latest version.

Many thanks.

**Comment by XceedBoucherS** [comment]
Hi,
You can go in file Xceed.Wpf.Toolkit/Obsolete/MaskedTextBox/Implementation/MaskedTextBox.cs,
and replace the "true" value in the Obsolete attribute for a "false" value.
