### ISSUE TITLE
Does DataGridControl in Extended WPF Toolkit have DataGrid.CellEditEnding 

### ISSUE THREAD

**Issue by TruePluto** [xceedsoftware/wpftoolkit#1230]
I want DataGridControl notificate applicaton when cell was changed. but I didn't find any thing in the DataGridControl relate to it.
Dose anybody tell me how to do?

**Comment by XceedBoucherS** [comment]
Hi,
Try adding handler to Cell.EditEnded event :
 _datagrid.AddHandler( Cell.EditEndedEvent, new RoutedEventHandler( this.EndEdit ) );

private void EndEdit( object sender, RoutedEventArgs e )
    {
      Cell button = e.OriginalSource as Cell;
    }
