### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by fahadbsse2693** [xceedsoftware/wpftoolkit#1231]
I found only  this "Xceed.Wpf.Samples.SampleData.dll" dll file in this clone,
I want to know How I use it in my Program?

**Comment by XceedBoucherS** [comment]
Hi,

When you clone "xceedsoftware/wpftoolkit", you have to open "ExtendedWPFToolkitSolution/Xceed.Wpf.Toolkit.sln" with Visual  Studio and compile it. This will generate the wanted dlls in "ExtendedWPFToolkitSolution\Src\Xceed.Wpf.Toolkit.LiveExplorer\bin\Debug" (if you compile for Debug mode).
In addition, you will be able to run the LiveExplorer to test all the Toolkit's controls.
