### ISSUE TITLE
DateTimePicker Minimum / Maximum Crash when Datepart changed via Keyboard

### ISSUE THREAD

**Issue by RambaaZambaa** [xceedsoftware/wpftoolkit#1232]
The DateTimePicker crashes when values under the Minimum or over the Maximum are typed in with the keyboard. For example: Maximum 05.12.2017 22:00:00, Value 05.12.2017 22:00:00. Now i selected the Datepart and enter 06, select a different part to switch focus and update the value
=> Crash
Tried with custom and default Format.

System.ArgumentOutOfRangeException occurred
  HResult=0x80131502
  Message=Value must be less than MaxValue of 05.12.2017 22:00:00
Parametername: Maximum

**Comment by XceedBoucherS** [comment]
Hi,
Try setting the Property ClipValueToMinMax to true.
This will prevent values from being greater than Maximum or lower than Minimum.
