### ISSUE TITLE
Show all Decimals in DoubleUpDown

### ISSUE THREAD

**Issue by TobHen** [xceedsoftware/wpftoolkit#1238]
Hi,
I am sorry for asking here, but I couldn’t find a solution yet and neither find a place where I can could ask other than here.
Currently I am using the community edition and the doubleupdown for numerical userinputs. Now I want to always show all decimals. Let’s say, I limit the control for 2 decimals and the user enters 2, then I would expect that the control shows 2.00.

Does anyone know if there is a way to make it work?

**Comment by XceedBoucherS** [comment]
Hi,
Try by setting the FormatString property : 
 <xctk:DoubleUpDown FormatString="N2" />
