### ISSUE TITLE
AvalonDock 3.5: DockAsDocument() stops working

### ISSUE THREAD

**Issue by IvanMakarevich** [xceedsoftware/wpftoolkit#1241]
AvalonDock 3.5.17430.11120: DockAsDocument() stops working after removing some items from AnchorablesSource.
Steps to reproduce:
Initial state: DockingManager with AnchorablesSource. AnchorablesSource have three items. Items docked to side panel (default).

1. Click on second anchorable to make it active.
2. Click on "Dock as Tabbed Document" context menu on second anchorable.
3. Remove first anchoarble (docked) from AnchorablesSource collection.
4. Remove second anchorable(tabbed) from AnchorablesSource collection.
5. Use context menu "Dock as Tabbed Document" on last anchoarble (docked).
6. Bug!!! nothing happens. Last anchorable do not switch to TabbedDocument
Even call to .DockAsDocument() from code do nothing.

Sample project in attachment
[AvalonDockBug.zip](https://github.com/xceedsoftware/wpftoolkit/files/1602927/AvalonDockBug.zip)

Is there any workaround or fix?

**Comment by XceedBoucherS** [comment]
Hi,

Toolkit v3.6 already has a fix for this. It will be released in January 2018.
I suggest you wait for this version, it's a question of days.
Thanks.
