### ISSUE TITLE
How to change DataTemplate in WatermarkTextBox?

### ISSUE THREAD

**Issue by 01joy** [xceedsoftware/wpftoolkit#1251]
Hi,

I used WatermarkTextBox in my xaml code:

```
<extToolkit:WatermarkTextBox x:Name="used_for_txt" Margin="5" TextWrapping="Wrap" AcceptsReturn="True">
	<extToolkit:WatermarkTextBox.WatermarkTemplate>
		<DataTemplate>
			<TextBlock x:Name="my_tag" Text="Enter new tags here separated by commas. They will all be applied when this window is closed." TextWrapping="Wrap" />
		</DataTemplate>
	</extToolkit:WatermarkTextBox.WatermarkTemplate>
</extToolkit:WatermarkTextBox>
```

I can't access my_tag TextBlock. How do I change TextBlock  my_tag.Text in *.cs code dynamically?

Thanks.

**Comment by XceedBoucherS** [comment]
Hi,
Define your WatermarkTextBox this way : 
  <xctk:WatermarkTextBox x:Name="used_for_txt"
                           Margin="5"
                           TextWrapping="Wrap"
                           Watermark="Enter new tags here separated by commas. They will all be applied when this window is closed."
                           AcceptsReturn="True">
      <xctk:WatermarkTextBox.WatermarkTemplate>
        <DataTemplate>
          <TextBlock x:Name="my_tag"
                     Text="{Binding}"
                     TextWrapping="Wrap" />
        </DataTemplate>
      </xctk:WatermarkTextBox.WatermarkTemplate>
    </xctk:WatermarkTextBox>

You will be able to modify the "Watermark" property.
