### ISSUE TITLE
Avalon Dock Fix docked Controls' size

### ISSUE THREAD

**Issue by raytangRT** [xceedsoftware/wpftoolkit#1254]
I am trying to make a dashboard like application on wpf using Avalondock, but the docking controls will make the control stretched and all alignments are gone, can someone give me some pointer?

![2018-01-23 17_03_52](https://user-images.githubusercontent.com/30689714/35266926-a907095c-005f-11e8-987e-7491d7f000b9.png)

**Comment by XceedBoucherS** [comment]
Hi,

You should be able to set the DockWidth property on LayoutAnchorablePane.
