### ISSUE TITLE
Column Names with "."

### ISSUE THREAD

**Issue by MPapst** [xceedsoftware/wpftoolkit#1257]
Is it possible in any way to have dots in the column names without having the data Grid rendering empty cells for those columns?

For the regular WPF datagrid there is a workaround by overriding the binding of these columns, but the event used there is not available in the xceed datagrid.
( https://stackoverflow.com/questions/2940618/what-is-it-about-datatable-column-names-with-dots-that-makes-them-unsuitable-for )

I am getting the following error for all columns with a dot name:
`https://stackoverflow.com/questions/2940618/what-is-it-about-datatable-column-names-with-dots-that-makes-them-unsuitable-for`

**Comment by XceedBoucherS** [comment]
Hi,

This is fixed in v3.3.
Users of the Plus edition are currently at v3.6.
Community edition v3.3 should be released shortly.
Thank you.

**Comment by MPapst** [comment]
Finally got a chance to give it a try.
Works good with 3.4 Community.

Thanks!
