### ISSUE TITLE
How to set a string property to multi-line in the PropertyGrid

### ISSUE THREAD

**Issue by jliliamen** [xceedsoftware/wpftoolkit#1264]
How to set a string property to multi-line in the PropertyGrid. Thanks! No Xaml!

**Comment by XceedBoucherS** [comment]
Hi,

In v3.3, you will be able to do : 
 <StackPanel>
    <Button x:Name="_myButton"
            Content="TEST" />
    <xctk:PropertyGrid SelectedObject="{Binding ElementName=_myButton}"
                       Width="300">
      <xctk:PropertyGrid.EditorDefinitions>
        <xctk:EditorTemplateDefinition TargetProperties="Content">
          <xctk:EditorTemplateDefinition.EditingTemplate>
            <DataTemplate>
              <TextBox Text="{Binding Value}"
                       TextWrapping="Wrap" />
            </DataTemplate>
          </xctk:EditorTemplateDefinition.EditingTemplate>
        </xctk:EditorTemplateDefinition>
      </xctk:PropertyGrid.EditorDefinitions>
    </xctk:PropertyGrid>
  </StackPanel>

Users of the Plus Edition are already at v3.6. You can get it here : https://xceed.com/xceed-toolkit-plus-for-wpf/
Community Edition v3.3 should be released shortly.

**Comment by XceedBoucherS** [comment]
Copy-Paste is not working. Here's the code again : 
` <StackPanel>
    <Button x:Name="_myButton"
            Content="TEST" />
    <xctk:PropertyGrid SelectedObject="{Binding ElementName=_myButton}"
                       Width="300">
      <xctk:PropertyGrid.EditorDefinitions>
        <xctk:EditorTemplateDefinition TargetProperties="Content">
          <xctk:EditorTemplateDefinition.EditingTemplate>
            <DataTemplate>
              <TextBox Text="{Binding Value}"
                       TextWrapping="Wrap" />
            </DataTemplate>
          </xctk:EditorTemplateDefinition.EditingTemplate>
        </xctk:EditorTemplateDefinition>
      </xctk:PropertyGrid.EditorDefinitions>
    </xctk:PropertyGrid>
  </StackPanel>`

**Comment by jliliamen** [comment]
Actually, I specifically mentioned that I didn't to achieve this using XAML. I have figured it out in my own.
For future references: https://stackoverflow.com/questions/48724673/multi-line-string-in-propertygrid-extended-wpf-toolkit-without-xaml/48838490#48838490
