### ISSUE TITLE
LayoutAnchroable - Click event

### ISSUE THREAD

**Issue by rajasri-muthaiya** [xceedsoftware/wpftoolkit#1265]
Is there any option to handle LayoutAnchroable click event. I need to perform some action when the tab is clicked.

**Comment by XceedBoucherS** [comment]
Hi,

You could always registered to the LayoutAnchorable.IsActiveChanged event. 
It will be triggered when a LayoutAnchorable becomes the active content or it not the active content anymore. You can look at its IsActive property.
