### ISSUE TITLE
DateTimeUpDown UpdateValueOnEnterKey cannot be set

### ISSUE THREAD

**Issue by rdstevens** [xceedsoftware/wpftoolkit#1266]
Documentation indicates that UpdateValueOnEnterKey can be set. Xaml editor gives a warning and control throws an exception if set attempt is made. Update documentation?

**Comment by XceedBoucherS** [comment]
Hi,

UpdateValueOnEnterKey is true by default for : 
-DateTimePicker
-DateTimeUpDown
-TimePicker
Modify it will throw an error for those 3 controls to prevent editing-validating problems.

UpdateValueOnEnterKey is false by default for other UpDown controls and can be modified.

The documentation will be updated.
Thank you.
