### ISSUE TITLE
Hide fully-qualified class name of ExpandableObject in PropertyGrid

### ISSUE THREAD

**Issue by blueshift777** [xceedsoftware/wpftoolkit#1268]
How do I hide the fully-qualified class name of an expandable object in the PropertyGrid?  See [this StackOverflow question](https://stackoverflow.com/questions/48788574/xceed-propertygrid-how-to-hide-fully-qualified-name-for-expandableobject) for a screenshot of the text that I wish to hide.

**Comment by XceedBoucherS** [comment]
Hi,

You can override the ToString method on your Expandable object : 
public override string ToString()
    {
      return this.FirstName + " " + this.LastName;
    }
