### ISSUE TITLE
PropertyGrid combobox binding

### ISSUE THREAD

**Issue by CajoHeikki** [xceedsoftware/wpftoolkit#1269]
How can I add property into propertygrid which is linked into combobox. In combobox selected item (which is custom class) should have template which contains two textblock and both have bindings from combobox item. Also in dropdown items should have these two textblocks.
I can get this work in standard xaml code but not when in propertygrid. I have basic toolkit (free).

**Comment by XceedBoucherS** [comment]
Hi,
Can you give more details, images, sample code ? How does it look like in standard xaml ?
We are trying to understand exactly what you want to do.
Thank you.

**Comment by CajoHeikki** [comment]
So I have already combobox which is not in propertygrid and it works with code:

```
            <ComboBox SelectedItem="{Binding Path=SelectedPen}" Grid.Row="0" Grid.Column="1" Grid.ColumnSpan="2" ItemsSource="{Binding Path=PenIdList}" Margin="0">
                <ComboBox.ItemTemplate>
                    <DataTemplate>
                        <StackPanel Orientation="Horizontal">
                            <TextBlock Width="16" Height="16" Margin="2" Background="{Binding PenColor}"/>
                            <TextBlock Height="16" Margin="2" Text="{Binding PenName}" HorizontalAlignment="Right"/>
                        </StackPanel>
                    </DataTemplate>
                </ComboBox.ItemTemplate>
            </ComboBox>
```
And it should look like this, but I can't get this work in propertygrid. Should be simple but I am not so familiar with PropertyGrid yet.

![kuva](https://user-images.githubusercontent.com/36691050/36594148-a7f6e718-18a5-11e8-982e-2f1339a71d7b.png)

**Comment by CajoHeikki** [comment]
Any information about this?

**Comment by CajoHeikki** [comment]
Any information about this?

**Comment by XceedBoucherS** [comment]
Hi,

Try defining an editor (of type CheckBox) for this property. Something like : 
 <xctk:PropertyGrid SelectedObject="{Binding}">
      <xctk:PropertyGrid.EditorDefinitions>
        <xctk:EditorTemplateDefinition TargetProperties="SelectedPen">
          <xctk:EditorTemplateDefinition.EditingTemplate>
            <DataTemplate>
              <ComboBox SelectedItem="{Binding Path=Value}"
                        Grid.Row="0"
                        Grid.Column="1"
                        Grid.ColumnSpan="2"
                        ItemsSource="{Binding Path=PenIdList, RelativeSource={RelativeSource AncestorType={x:Type Window}}}"
                        Margin="0">
                <ComboBox.ItemTemplate>
                  <DataTemplate>
                    <StackPanel Orientation="Horizontal">
                      <TextBlock Width="16"
                                 Height="16"
                                 Margin="2"
                                 Background="{Binding PenColor}" />
                      <TextBlock Height="16"
                                 Margin="2"
                                 Text="{Binding PenName}"
                                 HorizontalAlignment="Right" />
                    </StackPanel>
                  </DataTemplate>
                </ComboBox.ItemTemplate>
              </ComboBox>
            </DataTemplate>
          </xctk:EditorTemplateDefinition.EditingTemplate>
        </xctk:EditorTemplateDefinition>
      </xctk:PropertyGrid.EditorDefinitions>
    </xctk:PropertyGrid>


  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();

      this.PenIdList = new List<MyPen>()
      {
        new MyPen() { PenName = "Black", PenColor = new SolidColorBrush( Colors.Black ) },
        new MyPen() { PenName = "Blue", PenColor = new SolidColorBrush( Colors.Blue ) },
        new MyPen() { PenName = "Red", PenColor = new SolidColorBrush( Colors.Red ) },
      };

      this.DataContext = new MyObject()
      {
        Name = "My Data"
      };
    }

    public List<MyPen> PenIdList
    {
      get;
      set;
    }
  }

  public class MyObject
  {
    public string Name
    {
      get;
      set;
    }
    public MyPen SelectedPen
    {
      get;
      set;
    }
  }

  public class MyPen
  {
    public Brush PenColor
    {
      get;
      set;
    }

    public string PenName
    {
      get;
      set;
    }
  }

**Comment by kabircosta** [comment]
Mr. @XceedBoucherS , one question about it:
How Binding the object inside the **EditorTemplateDefinition.EditingTemplate** with the **SelectObject.Property**?
I did the test to serve the **ComboBox.SelectedItem** with the **xctk:PropertyGrid.SelectedObject property**, but it is not serving. Could you help me in this regard?

```
<xctk:PropertyGrid.EditorDefinitions> 
    <xctk:EditorTemplateDefinition TargetProperties="Material"> 
        <xctk:EditorTemplateDefinition.EditingTemplate> 
            <DataTemplate> 
                <ComboBox ItemsSource="{Binding Source={StaticResource materials}}" 
                                        SelectedItem="{Binding Path=Material, Mode=TwoWay}"/> 
            </DataTemplate> 
        </xctk:EditorTemplateDefinition.EditingTemplate> 
    </xctk:EditorTemplateDefinition> 
</xctk:PropertyGrid.EditorDefinitions> 
```
