### ISSUE TITLE
DynamicObject was NOT supported by DataGridControl V3.3.0 

### ISSUE THREAD

**Issue by TruePluto** [xceedsoftware/wpftoolkit#1274]
Today I upgrade the Extended WPF Toolkit package to version 3.30 from version 3.20
But frustration followed. All these members via DynamicObject.TryGetMember DynamicObject.TryGetIndex couldn't be binded properly. But when I downgrade to 3.20 everything is ok.
![v320](https://user-images.githubusercontent.com/19511177/37025659-43d15f78-2167-11e8-98de-328bc2742444.JPG)V3.20
![v330](https://user-images.githubusercontent.com/19511177/37025660-4408210c-2167-11e8-84a0-a8c010ac61f1.JPG)V3.30

saddly the version 3.2.0 was deleted from the Nuget list. 
Today is not a good day to coding.
wasted one day.
THANK YOU for your attention

**Comment by madenaras** [comment]
I have exactly the same problem and reverted to 3.2.0.

**Comment by TruePluto** [comment]
I just don't understand why a new version with major changes released without testing

**Comment by XceedBoucherS** [comment]
Hi,
Sorry about that.
Could you send us a sample showing the issue ? We would like to reproduce exactly the same issue as you found it.
Thank you.

**Comment by TruePluto** [comment]
I coded the issue in a solution with three project 
DynamicObjectDataGridSample used v3.3.0 and
DynamicObjectDataGridSampleOld used v3.3.0 
[DynamicObjectDataGridSample.zip](https://github.com/xceedsoftware/wpftoolkit/files/1846052/DynamicObjectDataGridSample.zip)
and I appreciate your attention.

**Comment by XceedBoucherS** [comment]
Thanks for the sample. 
We can reproduce the issue.
We will investigate to fix it.

**Comment by TruePluto** [comment]
Does the xceedsoftware/wpftoolkit project stay alive?

**Comment by XceedBoucherS** [comment]
Hi,
Yes, this is the free version of "Xceed Toolkit Plus for WPF" available here : https://xceed.com/xceed-toolkit-plus-for-wpf/.
xceedsoftware/wpftoolkit is still active as we read the issues you found and try to fix them in the "Plus" and "free" versions.
Thank you.
