### ISSUE TITLE
Mask property of MaskedTextBox not accepting "&&" as input

### ISSUE THREAD

**Issue by jb-work** [xceedsoftware/wpftoolkit#1279]
I am trying to create a MAC address MaskedTextBox, however whenever I input the "&" symbol there is a error that says _Expected the following token: ";"_.

Should I be using one of the other masking elements for this?

**Comment by XceedBoucherS** [comment]
Hi,
According to https://msdn.microsoft.com/en-us/library/system.windows.forms.maskedtextbox.mask(v=vs.110).aspx, the "&" character is used in a mask for : 
"Character, required. If the AsciiOnly property is set to true, this element behaves like the "L" element."

When you define the MaskedTextBox in XAML, try using "&amp;", which is the string equivalent to "&".
