### ISSUE TITLE
DataGridCollectionView Filter no longer works in v3.3.0

### ISSUE THREAD

**Issue by lipchev** [xceedsoftware/wpftoolkit#1287]
My code is based on the first example on this page:
https://xceed.com/wp-content/documentation/xceed-datagrid-for-wpf/Filtering_Data.html
Using DataGridCollectionView as items source and using a custom Predicate<object> for the Filter property.
It used to work in v3.2.0, now it doesn't.

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v3.4.
In the meantime, you can replace the 2 following files in Xceed.Wpf.DataGrid\(CollectionView) : 


[(CollectionView).zip](https://github.com/xceedsoftware/wpftoolkit/files/1843362/CollectionView.zip)
