### ISSUE TITLE
Datagrid rows disappear after edit when using DataGridCollectionViewSource

### ISSUE THREAD

**Issue by jetimmins** [xceedsoftware/wpftoolkit#1292]
- **Entering and then leaving cell edit causes that row to disappear from the DataGridControl. The underlying data is unaffected.**
- Refreshing ItemsSource in the codebehind then displays the data again.
- This does not happen when binding the DataGridControl ItemsSource directly to the property instead of using a DataGridCollectionViewSource.

- Issue as of v3.3
- Tested this in a completely barebones fresh solution (made a single DataGridControl with the ItemsSource bound to a DataGridCollectionViewSource as a static resource as per documentation, made a sample ObservableCollection of a simple POCO model).

I first suspected this was due to some filtering setup in my main project, however after eliminating features one by one and eventually recreating the problem in a fresh solution, it appears there's some issue with DataGridCollectionViewSource in v3.3.

**Comment by XceedBoucherS** [comment]
Hi, can you try it after an update of the 2 files  from 
https://github.com/xceedsoftware/wpftoolkit/issues/1287
If it works, than v3.4 includes the fix.

**Comment by jetimmins** [comment]
Rebuilt the .dll using your files and the bug appears to be fixed.
