### ISSUE TITLE
AvalonDock 3.3.0.0 FloatingWindowStyle

### ISSUE THREAD

**Issue by stelios84** [xceedsoftware/wpftoolkit#1301]
I am trying to restyle Create my own template for floatingWindows
I couldn't find any samples on internet.
I try the following.. 
 
please note that i did not include any theme reference.

` <ad:DockingManager.Resources>
                <Style TargetType="{x:Type ad:LayoutAnchorableFloatingWindowControl}">
                    <Setter Property="Template">
                        <Setter.Value>
                            <ControlTemplate TargetType="{x:Type ad:LayoutAnchorableFloatingWindowControl}">
                                <Label Content="test nothing to show.."></Label>
                            </ControlTemplate>
                        </Setter.Value>
                    </Setter>
                </Style>
            </ad:DockingManager.Resources>
`
when i undock one of my documents the window dose not rendered with my custom style / template

**Comment by Symbai** [comment]
I have the same issue

**Comment by stelios84** [comment]
did you find any workaround for that? any solution?

**Comment by Symbai** [comment]
Sadly no, I gave up and using a different docking control, I'm sorry.

**Comment by stelios84** [comment]
can you tell me what you are using so i can give it a look? Thanks..

**Comment by XceedBoucherS** [comment]
Hi,

Try setting it in App.xaml. Since it creates a new Window, it will take its resources in App.xaml : 

 <Application.Resources>
    <Style TargetType="{x:Type xcad:LayoutAnchorableFloatingWindowControl}">
      <Setter Property="BorderBrush"
              Value="Red" />
      <Setter Property="Template">
        <Setter.Value>
          <ControlTemplate TargetType="{x:Type xcad:LayoutAnchorableFloatingWindowControl}">
            <Border x:Name="WindowBorder"
                    BorderThickness="{TemplateBinding BorderThickness}"
                    Background="{TemplateBinding Background}"
                    BorderBrush="{TemplateBinding BorderBrush}">
              <Label Content="test nothing to show.."></Label>
            </Border>
          </ControlTemplate>
        </Setter.Value>
      </Setter>
    </Style>
  </Application.Resources>

**Comment by XceedBoucherS** [comment]
Again : 
` <Application.Resources>
    <Style TargetType="{x:Type xcad:LayoutAnchorableFloatingWindowControl}">
      <Setter Property="BorderBrush"
              Value="Red" />
      <Setter Property="Template">
        <Setter.Value>
          <ControlTemplate TargetType="{x:Type xcad:LayoutAnchorableFloatingWindowControl}">
            <Border x:Name="WindowBorder"
                    BorderThickness="{TemplateBinding BorderThickness}"
                    Background="{TemplateBinding Background}"
                    BorderBrush="{TemplateBinding BorderBrush}">
              <Label Content="test nothing to show.."></Label>
            </Border>
          </ControlTemplate>
        </Setter.Value>
      </Setter>
    </Style>
  </Application.Resources>`
