### ISSUE TITLE
Xceed CheckListBox Control Style

### ISSUE THREAD

**Issue by BhavnaBatra** [xceedsoftware/wpftoolkit#1302]
Issue: - Can anyone let me know how can we change the style of Check Box in Xceed CheckListBox control which includes Grid(PART_CHECKBOX) -> Rectangle ->Border -> Path -> Fill so that color of the path can be change according to our choice/theme?
We need to change Fill color of path in checkbox of CheckListBox which uses HighlightBrush color
As per current changes, we are changing HighLight color of Checkbox it is unable to change check mark of check box in the control
Below is the code that I am using in the style for Selected Item of CheckListBox control to change the color
<SolidColorBrush x:Key="{x:Static SystemColors.HighlightBrush}" Color="Green" />

**Comment by XceedBoucherS** [comment]
Hi,
I can't see your code.

You will need to replace the CheckBox Template with your own.

Something like : 
` <xctk:CheckListBox ItemsSource="{Binding}">
      <xctk:CheckListBox.Resources>
        <Style TargetType="{x:Type CheckBox}">
          <Setter Property="Template">
            <Setter.Value>
              <ControlTemplate TargetType="{x:Type CheckBox}">
                <Grid x:Name="templateRoot"
                      Background="Transparent"
                      SnapsToDevicePixels="True">
                  <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto" />
                    <ColumnDefinition Width="*" />
                  </Grid.ColumnDefinitions>
                  <Border x:Name="checkBoxBorder"
                          BorderBrush="{TemplateBinding BorderBrush}"
                          BorderThickness="{TemplateBinding BorderThickness}"
                          Background="{TemplateBinding Background}"
                          HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                          Margin="1"
                          VerticalAlignment="{TemplateBinding VerticalContentAlignment}">
                    <Grid x:Name="markGrid">
                      <Path x:Name="optionMark"
                            Data="F1 M 9.97498,1.22334L 4.6983,9.09834L 4.52164,9.09834L 0,5.19331L 1.27664,3.52165L 4.255,6.08833L 8.33331,1.52588e-005L 9.97498,1.22334 Z "
                            Fill="Red"
                            Margin="1"
                            Opacity="0"
                            Stretch="None" />
                      <Rectangle x:Name="indeterminateMark"
                                 Fill="Blue"
                                 Margin="2"
                                 Opacity="0" />
                    </Grid>
                  </Border>
                  <ContentPresenter x:Name="contentPresenter"
                                    Grid.Column="1"
                                    Focusable="False"
                                    HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                    Margin="{TemplateBinding Padding}"
                                    RecognizesAccessKey="True"
                                    SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"
                                    VerticalAlignment="{TemplateBinding VerticalContentAlignment}" />
                </Grid>
                <ControlTemplate.Triggers>
                  
                  <Trigger Property="IsChecked"
                           Value="true">
                    <Setter Property="Opacity"
                            TargetName="optionMark"
                            Value="1" />
                    <Setter Property="Opacity"
                            TargetName="indeterminateMark"
                            Value="0" />
                  </Trigger>
                  <Trigger Property="IsChecked"
                           Value="{x:Null}">
                    <Setter Property="Opacity"
                            TargetName="optionMark"
                            Value="0" />
                    <Setter Property="Opacity"
                            TargetName="indeterminateMark"
                            Value="1" />
                  </Trigger>
                </ControlTemplate.Triggers>
              </ControlTemplate>
            </Setter.Value>
          </Setter>
        </Style>
      </xctk:CheckListBox.Resources>
    </xctk:CheckListBox>`
