### ISSUE TITLE
Panel page in wiki is not redirecting correctly

### ISSUE THREAD

**Issue by vuchl** [xceedsoftware/wpftoolkit#1303]
The Link to the Panels section in the wiki (https://github.com/xceedsoftware/wpftoolkit/wiki) is not working since it is missing the /wiki/ in the URL: https://github.com/xceedsoftware/wpftoolkit/Panels should be https://github.com/xceedsoftware/wpftoolkit/wiki/Panels

**Comment by XceedBoucherS** [comment]
Thanks.
We will fix this.
