### ISSUE TITLE
DateTimePicker not showing current time when opened

### ISSUE THREAD

**Issue by sitsmonty** [xceedsoftware/wpftoolkit#1307]
Hello,

When user opens the calendar control in DateTimePicker, today's date is selected by default but the time field is blank. If user selects date, only the date with time as  12:00:00 gets updated in parent control. Instead it should give the current time.
User has to manually click on the up or down arrow in the time filed to get to current date. Also the "month, year" text on top of the calendar is half visible. That is a inconvenient. Am I doing something wrong ? Here is my code -

<xt:DateTimePicker Value="{Binding Path=DateField, Mode=TwoWay}"  />

**Comment by XceedBoucherS** [comment]
This should be already fixed in the latest v4.0.2 version.
