### ISSUE TITLE
DependsOn

### ISSUE THREAD

**Issue by GenuineRex** [xceedsoftware/wpftoolkit#1312]
How do you trigger a ItemsSourceAttribute property to refresh in a PropertyGrid when it depends on another value.

e.g. I have a printer setting and a tray setting.  I want to dynamically generate printers (easily done) and then based on the selected printer dynamically generate a list of trays (not happening).

**Comment by XceedBoucherS** [comment]
Hi,

If you use the Plus version (available here : https://xceed.com/xceed-toolkit-plus-for-wpf/), you can use the "DependsOn" attribute.

Currently,
-Users of the Plus version have v3.6
-Users of the Free version from GitHub have v3.3

Users of the Plus version always have the latest version and more features.

There is also the "RefreshProperties" attribute which will refresh all the PropertyGrid propertyItem when activated.
