### ISSUE TITLE
MaskedTextBox.IsMaskCompleted usage

### ISSUE THREAD

**Issue by mijikin** [xceedsoftware/wpftoolkit#1314]
What is the use of the IsMaskCompleted and IsMaskFull properties? I'm unable to bind to them as they are read-only.

**Comment by mijikin** [comment]
Yes, I had already read the doc, thank you. My issue is that I was trying to bind these to properties in my view model, but found out that I could not because they are read-only. As such, they don't appear to be much useful.

**Comment by XceedBoucherS** [comment]
Well you can bind on them, but only one way to obtain their status: 
` <TextBox Text="{Binding IsMaskCompleted, ElementName=_maskedTextBox, Mode=OneWay}" />`

**Comment by mijikin** [comment]
Ok, the way you do it works.
What I was trying to do is something like 
`<xctk:MaskedTextBox  IsMaskCompleted="{Binding xxx,Mode=OneWay}" ... />`
where xxx is a boolean property in my view model.
But that gives me this "'IsMaskCompleted' property is read-only and cannot be set from markup."

**Comment by night2day** [comment]
Can someone explain why IsMaskComplete is not usable like mijikin wrote but with Mode=OneWayToSource
I use this in a mvvm scenario and like to be informed when the text Matches the mask.
In XAML it don't shows the attribute IsMaskComplete.

**Comment by night2day** [comment]
I got it work with the  solution of Athari (universal solution)
https://stackoverflow.com/questions/1083224/pushing-read-only-gui-properties-back-into-viewmodel
one can bound readonly properties to viewmodels via pipes. 
Simple and clean solution.
