### ISSUE TITLE
DateTimePicker using spinner after selecting date

### ISSUE THREAD

**Issue by heckl** [xceedsoftware/wpftoolkit#1324]
If you change the date then you use the spinner to change the second then the original date will be changed.

<wpfTool:DateTimePicker Text="{Binding MyDateTime}" Format="Custom" 
       FormatString="yyyy-MM-dd HH:mm:ss" AutoCloseCalendar="True"/>

**Comment by XceedBoucherS** [comment]
Dupplicate of https://github.com/xceedsoftware/wpftoolkit/issues/1323
