### ISSUE TITLE
Errors loading datagrid dynamically with previousy working code.

### ISSUE THREAD

**Issue by g-colton** [xceedsoftware/wpftoolkit#1327]
Previously working code, prior to upgrade to vs 2017, dotNET 4.7.1 and Xceed 3.3.0. 

Dynamically generating datagrid in code. As soon as datagrid attempts to display the datagrid by adding to a wpf grid (g.children.add()), it throws an object reference error (when using NuGet version 3,3,0, or "InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed." when using references to the source code from GitHub . Grid "g" is defined in xaml. 

private DataGridControl _dataGridAddresses = new DataGridControl { Margin = new Thickness(10, 10, 30, 10), Name = "_dataGridAddresses" };
g.Children.Add(_dataGridAddresses);

However, if I build the grid in xaml, it works fine.
<Grid Name="g" VerticalAlignment="Top" HorizontalAlignment="Left" Margin="0,0,0,0" Height="590" Width="800" >
        <xcdg:DataGridControl x:Name="_dataGridAddresses" Margin = "10, 10, 30, 10" />
    </Grid>

What is causing the error when the datagrid is built dynamically at run-time? 

I have several grids being built, and displayed on tabs that are built based on data being returned from a large database. building each tab and datagrid in xaml is more code being executed being that only certain tabs and datagrids are displayed each time.

**Comment by XceedBoucherS** [comment]
Hi,
This is a known issue. 
In the meantime, make sure to define a view to your table, something like : 
`DataGridControl _dataGridAddresses = new DataGridControl { Margin = new Thickness( 10, 10, 30, 10 ), Name = "_dataGridAddresses", View = new TableflowView() };`

**Comment by g-colton** [comment]
Will do! Thank you for your help!

Greg Colton
PIMLAR Solutions
www.pimlar.com
210-683-2336
