### ISSUE TITLE
IntegerUpDown keyboard input 

### ISSUE THREAD

**Issue by dovtabor** [xceedsoftware/wpftoolkit#1329]
Hi, 

I'm using IntegerUpDown (version 3.3.0) and I can't set the control to allow only integer values.

Code:
  <xctk:IntegerUpDown FormatString="N0" Value="0" Increment="1" Minimum="0" Width="50" ParsingNumberStyle="Integer" DisplayDefaultValueOnEmptyText="True" DefaultValue="0" />

Is that a bug or am I doing something wrong?
                          
Thanks.

**Comment by XceedBoucherS** [comment]
Hi, What do you mean by "The IntegerUpDown can't allow only integer values" ?

Pressing up or down buttons increment/decrement by 1...no decimal values. You can type decimals values, but the control is in "invalid" state : the up/down button are disabled and focusing away will revert to last valid value.

If you want to be able to type only digits, you could define your own IntegerUpDown, and intercept the text input to accept only digits.
