### ISSUE TITLE
Binding broken in DataGridContol's Column.CellContentTemplate after upgrade from 2.5 -> 3.3.0

### ISSUE THREAD

**Issue by martani** [xceedsoftware/wpftoolkit#1330]
I have a solution where there is a binding expression within a `Column.CellContentTemplate` which works as expected with the DataGrid control in version 2.5 (https://github.com/martani/Twitter-Archive-Eraser/blob/master/DeleteTweets.xaml#L98)

```
<xcdg:Column.CellContentTemplate>
  <DataTemplate>
    <CheckBox IsChecked="{Binding ToErase, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}"/>
  </DataTemplate>
</xcdg:Column.CellContentTemplate>
```
After upgrading to version 3.3.0, the binding does not work anymore: changing the underlying property does not update the UI and vice versa.

Is there a breaking change I'm not aware of that needs special handling?

Thanks.

**Comment by martani** [comment]
What seems to be broken is having a column with FieldName="."

**Comment by XceedBoucherS** [comment]
Hi,
This could already be fixed, but just to make sure, could you provide a sample so we could reproduce this ?
Thank you.

**Comment by martani** [comment]
I fixed this by changing
```
<xcdg:Column FieldName="." Title="Erase ?" CellEditorDisplayConditions="CellIsCurrent">
	<xcdg:Column.CellContentTemplate>
		<DataTemplate>
			<CheckBox IsChecked="{Binding ToErase, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}"/>
		</DataTemplate>
	</xcdg:Column.CellContentTemplate>
</xcdg:Column>
```
To
```
<xcdg:Column FieldName="."  Title="Erase ?"
		 DisplayMemberBinding="{Binding Path=ToErase, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
		 CellEditorDisplayConditions="CellIsCurrent">
	<xcdg:Column.CellContentTemplate>
		<DataTemplate>
			<CheckBox IsChecked="{xcdg:CellEditorBinding NotifyOnSourceUpdated=True}" />
		</DataTemplate>
	</xcdg:Column.CellContentTemplate>
</xcdg:Column>
```
