### ISSUE TITLE
ColorPicker cannot set to Red

### ISSUE THREAD

**Issue by NakamuraYuka** [xceedsoftware/wpftoolkit#1335]
Hello.
I am using color picker in my control. I want to set color Red(#FFFF0000) in the color picker.
But, pushing advanced button, set color Red(#FFFF0000) is changed to (#FFFF0004). 
Am I doing something wrong?

**Comment by XceedBoucherS** [comment]
Hi,
This can't be reproduced in v3.4 and up.
What version are you using ?
Any special steps to reproduce this ?
Thanks.

**Comment by NakamuraYuka** [comment]
Hi,

I'm using the version 2.1.0.
I will try again after updating.

Thank you.
