### ISSUE TITLE
NumericUpDown: Increment/decrement input stays disabled after moving away from Minimum/Maximum.

### ISSUE THREAD

**Issue by HerrNyani** [xceedsoftware/wpftoolkit#1348]
If the NumericUpDown `Value` is equal to `Minimum`, the down key is disabled. If I then press the up key to increment the value, the down key remains disabled, which means that I cannot return to the minimum value by pressing the down key. I can only keep incrementing the value.

The event can be re-enabled by pressing enter or leaving the control first, but I think the increment/decrement enable check should be evaluated whenever the actual value changes when using the up/down keys.

Setting the `Value` binding to `UpdateSourceTrigger=PropertyChanged` also doesn't fix the issue.

Tested with IntegerUpDown and DoubleUpDown controls.

EDIT: Using the up and down buttons on the control result in the same behavior.

**Comment by HerrNyani** [comment]
Temporary fix: Whenever the up or down key is released, fire a new event that simulates an enter key press.

Add to <UserControl>.xaml.cs:
```C#
private void NumericUpDown_OnKeyUp(object sender, KeyEventArgs e)
{
    if (e.Key == Key.Down || e.Key == Key.Up)
    {
        if (!(sender is UIElement uiElementSender))
        {
            return;
        }

        RaiseVirtualKeyDownEvent(uiElementSender, Key.Enter);
    }
}
        
private static void RaiseVirtualKeyDownEvent(UIElement sender, Key key)
{
    if (sender == null)
    {
        throw new ArgumentNullException(nameof(sender));
    }

    var inputSource = PresentationSource.FromVisual(sender);
    if (inputSource == null)
    {
        return;
    }

    var virtualEnterPressedEventArgs = new KeyEventArgs(
        Keyboard.PrimaryDevice, inputSource, 0, key)
    {
        RoutedEvent = Keyboard.KeyDownEvent
    };

    sender.RaiseEvent(virtualEnterPressedEventArgs);
}
```

Add to <UserControl>.xaml file:
```xaml
<UserControl.Resources>
    <Style TargetType="xctk:IntegerUpDown" BasedOn="{StaticResource {x:Type xctk:IntegerUpDown}}">
        <EventSetter Event="KeyUp" Handler="NumericUpDown_OnKeyUp" />
    </Style>
</UserControl.Resources>
```
Replace `IntegerUpDown` with the NumericUpDown control you use.

This will only update the control once you release the up or down key. Holding it will delay the check.

**Comment by XceedBoucherS** [comment]
Hi,
I cannot reproduce this in v3.4. 
As soon as the up key (or the Up button) is pressed, the down button is enabled.
Here's my control : 
` <xctk:IntegerUpDown Value="0"
                        Minimum="0" />`

**Comment by HerrNyani** [comment]
Hello
Thanks for checking the issue.

I have found the problem: I misinterpreted the UpdateValueOnEnterKey property as enabling the enter key to input data aside from a focus loss, instead of requiring an enter key press to update the value. Setting the property back to False results in the expected behavior.

My bad, closing this issue.
