### ISSUE TITLE
Avalon Dock - When reconnecting to a remote desktop session, floating windows close and throw an exception

### ISSUE THREAD

**Issue by VinnieBoiii** [xceedsoftware/wpftoolkit#1353]
When reconnecting to a remote desktop session on Windows 10, the DockingManager Unloaded event handler is called, as is the LayoutFloatingWindowControl Unloaded event handler, this causes an exception to get thrown because the LayoutFloatingWindowControl is trying to close twice.

As far as I'm aware, these events should not be triggered but reconnecting to a remote session seems to fire them.

Both of these are reproducible in the LiveExplorer, for the first one, enter the Avalon Dock section, drag the properties control out so it becomes a floating window, leave the remote desktop session, reconnect and then the exception should get thrown.

I am using Version 3.4.0, any help you could offer would be appreciated.

**Comment by XceedBoucherS** [comment]
Hi,
Can you reproduce this in the latest v3.7 version available here : https://xceed.com/xceed-toolkit-plus-for-wpf/

Thank you.

**Comment by VinnieBoiii** [comment]
The issue cannot be reproduced in v3.7

**Comment by XceedBoucherS** [comment]
Ok,
I suggest you wait for v3.7 has the fix is included in that release.
You can always buy it if you need it fast.
Thank you.
