### ISSUE TITLE
DateTimePicker and TimePicker value is not updated, when selected in dropdown or calendar

### ISSUE THREAD

**Issue by IlyaBezus** [xceedsoftware/wpftoolkit#1358]
As mentioned in title, value of related property is not updated before I click outside of control (after value is selected inside Calendar of DateTimePicker or dropdown of TimePicker), even when **Value**'s **UpdateSourceTrigger** is set to **PropertyChanged**. However, spinners are working fine.
Package version: 3.4.0 Community.

**Comment by XceedBoucherS** [comment]
Hi,

Opening the Calendar and selecting a date is considered the same as modifying the text. This means that the validation won't be done until the "Enter" key is pressed or the focus is moved away from the control.
Clicking on the Spinners will always result in a valid value so the validation is done right away. That is why the Value is immediately updated.

**Comment by IlyaBezus** [comment]
Could you please clarify if there there is any proper way of forcing validation after calendar of DateTimePicker or TimePicker's ComboBox value was changed?

**Comment by XceedBoucherS** [comment]
Hi,
You can create your own DateTimePicker, register to Calendar.SelectedDateChanged and update the Value : 
`public class MyDateTimePicker : DateTimePicker
  {
    public override void OnApplyTemplate()
    {
      base.OnApplyTemplate();

      var calendar = this.GetTemplateChild( "PART_Calendar" ) as Calendar;
      if( calendar != null )
      {
        calendar.SelectedDatesChanged += Calendar_SelectedDatesChanged;
      }
    }

    private void Calendar_SelectedDatesChanged( object sender, SelectionChangedEventArgs e )
    {
      this.CommitInput();
    }
  }`

**Comment by IlyaBezus** [comment]
Hello,
Sorry for bothering you again, but this trick only works for manually changing date from calendar. If I set DateTimePicker's Value from viewmodel (via Value binding), it is ignored and is set to null.

**Comment by XceedBoucherS** [comment]
Hi,
Can you paste a sample so we can execute the same as you ?
Thank you.

**Comment by IlyaBezus** [comment]
Hello,
Sure thing! Here is project with both types of datepickers and single timepicker.
[DateTimePickerTest.zip](https://github.com/xceedsoftware/wpftoolkit/files/2233163/DateTimePickerTest.zip)

Here are some repro steps to make it easier for you:

1. Manually select value from first datepicker.
2. It is not updated before you confirm input (as expected).
3. Hit 'Randomize'.
4. Both value and text are updated.

5. Manually select value from second datepicker.
6. It is updated right before you confirm input.
7. Hit 'Randomize'.
8. Only **property** value is updated, while text remains the same.

Optionally, steps 1-4 are applicable to timepicker.

**Comment by XceedBoucherS** [comment]
Hi,

Force the commit on the text changed callback, Here's your new DateTimePicker:
` public class MyDateTimePicker : DateTimePicker
    {
      protected override void OnTextChanged( string previousValue, string currentValue )
      {
        base.OnTextChanged( previousValue, currentValue );
        CommitInput();
      }
  }`

**Comment by IlyaBezus** [comment]
Hello. This is much better, however, manual changing of values in textbox is now incorrect (can't change day to '23', because input is commited after typing '2'). That's what I ended up with: 
```
public class AutoCommitInputDateTimePicker : DateTimePicker
{
    private Popup popup;

    public override void OnApplyTemplate()
    {
        base.OnApplyTemplate();
        popup = GetTemplateChild("PART_Popup") as Popup;
    }

    protected override void OnTextChanged(string previousValue, string currentValue)
    {
        base.OnTextChanged(previousValue, currentValue);

        if (popup != null && popup.IsOpen)
            CommitInput();
    }
}
```
Thanks a lot :)

**Comment by matt-entrekin** [comment]
Thanks! This solution worked for me.

I was able to simplify the class with the `DateTimePickerBase.IsOpen` property which is tracking the state of the popup.

```
public class AutoCommitInputDateTimePicker : DateTimePicker
{
    protected override void OnTextChanged(string previousValue, string currentValue)
    {
        base.OnTextChanged(previousValue, currentValue);
        if (IsOpen)
        {
            CommitInput();
        }
    }
}
```

**Comment by aday12345** [comment]
I am having the same issue with the time picker, as a user i would expect that selecting a time value from the drop down would be no different then incrementing a time with the spinners. As a developer i would expect that the ValueChanged event would be raised when a value is selected from the drop down currently it is not.

**Comment by XceedBoucherS** [comment]
Hi,

Thank you for the feedback.
v3.8 will be modified accordingly : 
-DateTimePicker : a new selection in the calendar will automatically modify the Value property.
-TimePicker : a new selection in the ListBox will automatically modify the Value property.

**Comment by aday12345** [comment]
when could we expect this fix to end up in the free version

**Comment by XceedBoucherS** [comment]
Hi,
v3.8 is the next version to be released (in the commercial version).

Currently, commercial version is v3.7 and free version is v3.4.
When the commercial version will upgrade to v3.8, the free version should upgrade to v3.5.
You can always try the free 45 days trial of the commercial version here : https://xceed.com/xceed-toolkit-plus-for-wpf/
The next upgrade should at the beginning of 2019.
Thank you.
