### ISSUE TITLE
Self-contradictory documentation on displaying MessageBox outside WindowContainer

### ISSUE THREAD

**Issue by MikeRosoft** [xceedsoftware/wpftoolkit#1363]
The documentation for ShowMessageBox at https://xceed.com/wp-content/documentation/xceed-toolkit-plus-for-wpf/Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.MessageBox~ShowMessageBox.html says: "Also, this method is not intended to be called while displaying a MessageBox outside of a WindowContainer. Use ShowDialog instead in that case."

The same sentence links to documentation of ShowDialog at https://xceed.com/wp-content/documentation/xceed-toolkit-plus-for-wpf/Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.MessageBox~ShowDialog.html , which says: "This method is not intended to be called while displaying a MessageBox outside a WindowContainer. Use ShowMessageBox instead" and links back to the documentation of ShowMessageBox.

If neither method is intended for showing a dialog box outside a WindowContainer, the documentation should be updated accordingly (include the sentence that "A MessageBox instance is not intended to be displayed in a container other than a WindowContainer" in both places and remove the misleading cross-references).

**Comment by XceedBoucherS** [comment]
Hi,

Thank you for reporting this.

The documentation in page https://xceed.com/wp-content/documentation/xceed-toolkit-plus-for-wpf/Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.MessageBox~ShowDialog.html
should be replaced.
"This method is not intended to be called while displaying a MessageBox outside a WindowContainer. Use ShowMessageBox instead."
should be replaced with:
"This method is not intended to be called while displaying a MessageBox **inside** a WindowContainer. Use ShowMessageBox instead."

Documentation will be updated.
