### ISSUE TITLE
DataGrid - remove the RowSelectorPane

### ISSUE THREAD

**Issue by leinad13** [xceedsoftware/wpftoolkit#1371]
Is it possible to remove the RowSelectorPane from the DataGrid. I have tried styling the RowSelector and RowSelector pane to hidden visibility which removes the grid lines and arrow but leaves the grey background box.

**Comment by XceedBoucherS** [comment]
Hi,

You can have a look at the example in the documentation page:
https://xceed.com/wp-content/documentation/xceed-toolkit-plus-for-wpf/webframe.html#Xceed.Wpf.DataGrid~Xceed.Wpf.DataGrid.RowSelectorPane.html
