### ISSUE TITLE
TimeSpanUpDown Exception at DesignTime

### ISSUE THREAD

**Issue by Streissi** [xceedsoftware/wpftoolkit#1374]
Hi i use the TimeSpanUpDown control and have a exception at designTime and at build.

designTime Exception:
![image](https://user-images.githubusercontent.com/26823133/44580029-af236480-a798-11e8-8980-2aa8e672f350.png)
sorry for the image but the designer shows only that window and i cant copy the exception.

Build Exception:
CurrentDateTimePart' property was already registered by 'Xceed_Wpf_Toolkit_Primitives_DateTimeUpDownBase`1_15_382374204'.

how i use the control:
`<xceed:TimeSpanUpDown Grid.Column="1"
                                      Grid.Row="1"/>`

Did i miss something?

**Comment by XceedBoucherS** [comment]
Hi,
This is related to the code design used with template in base classes. VisualStudio is having issues with this and show errors. But the compilation and run should work normally.

**Comment by Streissi** [comment]
hi, true, i missunterstod the error as build-error, it runs normaly only at design-time it shows an error.
