### ISSUE TITLE
TimeSpanUpDown crashes when numeric values are typed constantly on keyboard

### ISSUE THREAD

**Issue by ricardofnsc** [xceedsoftware/wpftoolkit#1385]
Using TimeSpanUpDown control, and if continuously a number is typed, after a while the control throws an exception and crashes. 

I noticed this issue on 3.3.0 version and then I updated it to 3.4.0 version, but the problem remains.

I searched for a similar issue and I found the following one (as you can see below)
https://github.com/xceedsoftware/wpftoolkit/issues/1232

There the workaround was to put the property ClipValueToMinMax to true, but it doesn't solve the issue.

Is there a fix for this issue or any workaround?

Thanks.

**Comment by XceedBoucherS** [comment]
related to https://github.com/xceedsoftware/wpftoolkit/issues/1321
