### ISSUE TITLE
Wizard Finish/Next button appear place

### ISSUE THREAD

**Issue by nickgrishaev** [xceedsoftware/wpftoolkit#1388]
Hi.
In v.3.3.0 was changed "Finish" button  appear place.
This is in v.3.3.0 change log written:
"the “Finish” button will now appear in place of the “Next” button when the property “CanFinish” becomes true."

How I can return previous behavior?
My finish page change "CanFinish" property dynamically. But then I set CanFinsh = false, the button Next does not become visible.

**Comment by XceedBoucherS** [comment]
Hi,

I cannot reproduce this behavior in v3.3.
Here's my sample : 
`<xctk:Wizard>
         <xctk:WizardPage Title="Welcome to my Wizard"
                          Description="This Wizard will walk you though how to do something." />
         <xctk:WizardPage PageType="Interior"
                          Title="Page 1"
                          Description="This is the first page in the process." />
         <xctk:WizardPage x:Name="_page3"
                          PageType="Interior"
                          Title="Page 2"
                          Description="This is the second page in the process">
            <StackPanel>
               <Button Content="Finish On"
                       Click="Button_Click" />
               <Button Content="Finish Off"
                       Click="Button_Click_1" />
            </StackPanel>
         </xctk:WizardPage>
         <xctk:WizardPage PageType="Interior"
                          Title="Last Page"
                          Description="This is the last page in the process" />
      </xctk:Wizard>`

` private void Button_Click( object sender, RoutedEventArgs e )
    {
      _page3.CanFinish = true;
    }

    private void Button_Click_1( object sender, RoutedEventArgs e )
    {
      _page3.CanFinish = false;
    }`

**Comment by nickgrishaev** [comment]
I found my problem.
To reproduce Add tag FinishButtonVisibility="Visible" to <xctk:WizardPage x:Name="_page3"...
With this tag Finish button always visible.  Next button is not accessible.

When I replace FinishButtonVisibility="Visible" to FinishButtonVisibility="Inherit" problem was gone.
