### ISSUE TITLE
Binding ObservableCollection to DocumentsSource causes memory leak

### ISSUE THREAD

**Issue by mennowo** [xceedsoftware/wpftoolkit#1408]
Hello. I have the same issue mentioned in #1033 , however the solution proposed in the final comment does not resolve this for me.
I bind an ObservableCollection to DocumentSource:
`<ad:DockingManager DocumentsSource="{Binding Path=Workspaces,Mode=OneTime}">`
I subscribe to the DocumentClosed event, and remove items that are closed from the bound collection.
```
dw.DocumentClosed += Dw_DocumentClosed;
private void Dw_DocumentClosed(object sender, Xceed.Wpf.AvalonDock.DocumentClosedEventArgs e)
{
    workspace.Workspaces.Remove((WorkspaceBase)e.Document.Content);
}
```
However, the LayoutDocumentPane internal to AvalonDock keeps references to all children, even after they are removed both from the view and from the bound collection.
Is this expected behaviour? I am using version 3.4.
Thanks, Menno

**Comment by XceedBoucherS** [comment]
Hi, 
Is this an issue with the latest version of the Xceed Toolkit Plus for WPF available for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/.
If yes, can you explain how you can see that AvalonDock keeps references to all children ? Please note that the Garbage collect is not always instant.
Thank you.

**Comment by mennowo** [comment]
Hello,
sorry be so slow to reply. I later found my own code to be the root cause of the problem. I built a small application to thoroughly test the GC in this case, and found that it does indeed run, though sometimes it takes a long time. Cause some of my ViewModels used a lot of space that was not freed directly when closing the related View, it seemed like the GC did not kick in. Thanks for your answer!
Menno
