### ISSUE TITLE
The words appear in vertical in RichTextBox

### ISSUE THREAD

**Issue by kintela** [xceedsoftware/wpftoolkit#1410]
Hi I have this RichtextBox
`<toolkit:RichTextBox Grid.Row="2" Height="80"
                                                 Text="{Binding Ubicacion.Observaciones, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                                                 ScrollViewer.VerticalScrollBarVisibility="Auto">
                                <toolkit:RichTextBox.TextFormatter>
                                    <toolkit:PlainTextFormatter></toolkit:PlainTextFormatter>
                                </toolkit:RichTextBox.TextFormatter>
                            </toolkit:RichTextBox>`
And when the text of the dependendy property is loaded or when I writeI see this:
![rtb](https://user-images.githubusercontent.com/10060242/48913330-59825500-ee78-11e8-82b4-ee4792859749.jpg)

Any idea Please?

Kind regards

**Comment by jamesnealon010687** [comment]
I have the same issue.

**Comment by XceedBoucherS** [comment]
Hi,
Please post a complete sample.
Trying the preceding sample works as expected with Toolkit v3.8.
Thank you.

**Comment by jamesnealon010687** [comment]
I have found the issues. RichTextBox requires a width.
