### ISSUE TITLE
TypeConverter of type StringConverter is not working PropertyGrid

### ISSUE THREAD

**Issue by niranjan0211** [xceedsoftware/wpftoolkit#1413]
I have a class which is implementing "StringConverter". Now I am using this class to decorate TypeConverter PropertyAttribute as shown below. InitalizedVariables implements "StringConverter" and it has dictionary member.

`
[Browsable(true)]
        [ReadOnly(false)]
        [Description("Select the initialized variable")]
        [Category("General")]
        [DisplayName("StartIndex")]
        [TypeConverter(typeof(InitalizedVariables))]
        public string Start
        {
            get { return _start; }
            set { _start = value;
                OnPropertyChanged("Start");
            }
        }
`

`
public class InitalizedVariables : StringConverter
    {
        public static Dictionary<string, int> Variables = new Dictionary<string, int>();

        public override bool GetStandardValuesExclusive(ITypeDescriptorContext context)
        {
            return false;
        }

        public override StandardValuesCollection GetStandardValues(ITypeDescriptorContext context)
        {
            string[] a = Variables.Select(x => x.Key).ToArray();
            return new StandardValuesCollection(a);
        }

        public override bool GetStandardValuesSupported(ITypeDescriptorContext context)
        {
            return true;
        }
    }`

This works fine in Windows forms application and I get edit value in propertygrid directly or I can select an item in the dictionary(dropdown) as shown below. 

![image](https://user-images.githubusercontent.com/43724452/49150540-34d42480-f333-11e8-9aef-4fdf02e2862b.png)

But this doesnt work in WPF if I use WPF toolkit propertygrid. I dont get the dropdown.
![image](https://user-images.githubusercontent.com/43724452/49150882-318d6880-f334-11e8-8fa9-e00c6873c5da.png)

How can I achieve the same thing in WP? Please guide me. Are there any alternative solution or approach??

**Comment by XceedBoucherS** [comment]
Hi,
Try returning true for 
GetStandardValuesExclusive.

**Comment by niranjan0211** [comment]
Thanks. That resolved my issue.
Forgot to close it.
Closing it now.
