### ISSUE TITLE
Cannot set null on UpDown

### ISSUE THREAD

**Issue by marshmit** [xceedsoftware/wpftoolkit#1417]
I'm having an issue with the IntegerUpDown Control - but I think its similar on other UpDowns. As I understand it should be able to handle nullable integers, but I cannot set it back to null if in the beginning the bound value has a non-null value.

The control is bound to an object and null is valid entry that the user should be able to make (or from the users point of view leaving the option empty) . If the initial value is null this works fine, but once I start with a (non null) value and delete the input the control sets it back to the initial value. I have tried setting DefaultValue to null, but that didn't help (as I was expecting since the documentation told me that should be the value that is used if it isn't null).

How can I achieve that the user can set it to null even if there was a value in the beginning?

**Comment by XceedBoucherS** [comment]
Hi, 
let's say I have the following xaml code: 
 <StackPanel>
    <xctk:IntegerUpDown x:Name="_integerUpDown"
                        Value="5" />
    <TextBox Text="{Binding Value, ElementName=_integerUpDown}"/>
</StackPanel>

If I click inside the IntegerUpDown and delete the "5" and then click inside the TextBox, the IntegerUpDown keeps a "null" value.

**Comment by marshmit** [comment]
Hi,
thank you for checking. You are right, after recreating my rather complex scenario in a small test project it behaves correctly as you describe. After much longer searching I found the cause for this behavior - completely unrelated to the WPFToolkit - in a model base class of the project I'm working on.
My apologies and thanks for the help.
