### ISSUE TITLE
Data saving issue with the PropertyGrid plugin

### ISSUE THREAD

**Issue by XzMitsui** [xceedsoftware/wpftoolkit#1422]
When I use the plugin to do my property panel, this problem occurs: when a row changes data, if the focus still exists, the background will not get the changed value and cause me to save the failure. On the contrary, if it is losing focus When saving, it will be saved successfully. I think this kind of behavior is very unfriendly to the user, and there is no solution in the documentation of the plugin. Can you explain it?

**Comment by XceedBoucherS** [comment]
Hi,
Can you submit an example ? What type of PropertyGrid properties ? When are you saving ?
Thank you.

**Comment by XzMitsui** [comment]
```
<Grid>
        ...
        <xceed: PropertyGrid Grid.Row="1"
                             BorderThickness="0"
                             ShowSearchBox="False"
                             ShowTitle="False"
                             SelectedObject="{Binding Selected.Property}">
         </xceed:PropertyGrid>
</Grid>
```
Hey, this is the way we use it in View, because our company has internal and external networks, and can't send out company projects. For example, when using VS, modify the properties of a project's file in the properties panel and save the operation. We want to change the data if the panel loses focus (I click with the mouse outside the panel) or use Ctro+S to save the data, but now I can't do this, I modified the value of a textblock, this When the mouse focus is still on this control, I can't successfully save the data using Ctro+S.

**Comment by XzMitsui** [comment]
> ```
> <Grid>
>         ...
>         <xceed: PropertyGrid Grid.Row="1"
>                              BorderThickness="0"
>                              ShowSearchBox="False"
>                              ShowTitle="False"
>                              SelectedObject="{Binding Selected.Property}">
>          </xceed:PropertyGrid>
> </Grid>
> ```
> 嘿，这是我们在View中使用它的方式，因为我们公司有内部和外部网络，不能发送公司项目。例如，使用VS时，在属性面板中修改项目文件的属性并保存操作。我们想要更改数据，如果面板失去焦点（我在面板外单击鼠标）或使用Ctro + S保存数据，但现在我不能这样做，我修改了一个文本块的值，这时候鼠标焦点仍在此控件上，我无法使用Ctro + S成功保存数据。

@XceedBoucherS

**Comment by XceedBoucherS** [comment]
Hi,
Just make sure to put the focus away before saving. This way, the selected propertyItem value will be updated on the bound object. Then, you can set back the focus on the propertyItem : 
 protected override void OnKeyDown( KeyEventArgs e )
    {
      base.OnKeyDown( e );

      if( ( e.Key == Key.S ) && ( Keyboard.Modifiers == ModifierKeys.Control ) )
      {
        var focusedElement = FocusManager.GetFocusedElement( this );
        _propertyGrid.Focus();
        var savedElement = this.Selected;
        focusedElement.Focus();
      }
    }

**Comment by XzMitsui** [comment]
@XceedBoucherS Hello, so it seems to be writing code in the logical page of the view? Because we follow the pure MVVM mode, generally do not let the logic code here, is there any other way?Thanks.

**Comment by XzMitsui** [comment]
@XceedBoucherS  I found out It turns out that it has the properties of the control.Now it works,I get it 
```
<Grid>
        ...
        <xceed: PropertyGrid Grid.Row="1"
                             BorderThickness="0"
                             ShowSearchBox="False"
                             ShowTitle="False"
                             SelectedObject="{Binding Selected.Property}">
            <i:Interaction.Triggers>
                  <i:EventTrigger EventName="LostFous">
                         <i:InvokeCommandAction Command="{AcionName}"
                             CommandParamter="{Binding}"/>
                  </i:EventTrigger>
            </i:Interaction.Triggers>
         </xceed:PropertyGrid>
</Grid>
```
