### ISSUE TITLE
Styling UpDown spinners

### ISSUE THREAD

**Issue by randohinn** [xceedsoftware/wpftoolkit#1429]
The old codeplex links do not work. Is there any way to style the Up/Down buttons on these components? For example, to get something like shown in the included pic?
![udown](https://user-images.githubusercontent.com/14096473/51348757-24773500-1aac-11e9-8fc6-37546eb4689e.PNG)

**Comment by XceedBoucherS** [comment]
Hi,

You will have to modify the styles and templates of the NumericUpDowns.
For example, a DoubleUpDown includes a control named ButtonSpinner (2 RepeatButtons and a WatermarkTextBox).
The ButtonSpinner defines the RepeatButtons styles. Theses styles are defined by SpinnerButtonStyleKey as ButtonChrome.
Finally, ButtonChrome defines the content, borders and click event.
You can find all these templates in the sources of the project.

**Comment by randohinn** [comment]
Okay, will investigate
