### ISSUE TITLE
AvalonDock detect item is tabbed or floating

### ISSUE THREAD

**Issue by FabioGenesy** [xceedsoftware/wpftoolkit#1437]
Hi,
I use AvalonDock version 2.1.0 and I create dynamic LayoutAnchorable item by an AnchorableSource list of element. 
I'm not clear how I can understand when a LayoutAnchorable item is tabbed or is floating.
I didn't find a specific floating event and the property IsFloating I look is always false even when the  LayoutAnchorable item is not tabbed.
Is it a known bug of this version or am I wrong?
Thank you very much!

**Comment by XceedBoucherS** [comment]
Hi,
Can you try this in the latest version to see if you it is fixed ? Latest version is v3.8 and is available for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/
Thank you.

**Comment by FabioGenesy** [comment]
I tried also the new version but is the same

**Comment by XceedBoucherS** [comment]
Hi,
you can try something like this:
 public MainWindow()
    {
      InitializeComponent();
      this.DataContext = this;
      this.MyAnchorables = new List<Button>() { new Button() { Content = "First" }, new Button() { Content = "Second" } };
      _dockingManager.Layout.FloatingWindows.CollectionChanged += FloatingWindows_CollectionChanged;
    }

    private void FloatingWindows_CollectionChanged( object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e )
    {
      var floatingWindowAdded = e.NewItems[ 0 ] as LayoutFloatingWindow;
      if( floatingWindowAdded != null )
      {
        var anchorableActive = floatingWindowAdded.Descendents().OfType<LayoutAnchorable>().FirstOrDefault();
        var isFloating = anchorableActive.IsFloating;
      }
    }
