### ISSUE TITLE
AutoCompleteBox - Drawing issues when moving or resizing window

### ISSUE THREAD

**Issue by SiL3NC3** [xceedsoftware/wpftoolkit#1444]
**AutoCompleteBox**

Hi there, got some issues with AutoCompleteBox:
When moving or resizing a window with opened dropdown area, the AutoCompleteBox is not sizing properly to the textbox (on window resizing) and not moving with the window (on window move/drag).
On moving it just stays at the same position.
Was following the example of: https://www.broculos.net/2014/04/wpf-autocompletebox-autocomplete-text.html

Is this a bug? How can this be fixed?

Window resizing (no problem on enlarging, just on reducing):
![autocompletebox_windowresizing](https://user-images.githubusercontent.com/694970/52486992-e2c63f80-2bbc-11e9-89a8-05cadb801cc2.jpg)

Window moving / dragging:
![autocompletebox_windowmoving](https://user-images.githubusercontent.com/694970/52486991-e22da900-2bbc-11e9-88dc-19e3efad9800.jpg)

**Comment by Dirkster99** [comment]
Thats a funny issue - its actually not a drawing issue but an issue of missing event handlers and reactions to that. The control is obviously to processing resize events of the hosting window in this case. I've seen a similare problem when I developed a similar pop-up control :-) The solution is to:
- try and find the hosting window
- attach various event handlers
- and process the events (almost always by closing the pop-up) and only re-opening on certain events like activation, focus etc.

- you can see a solution to this if you look [at this code](https://github.com/Dirkster99/SuggestBoxLib/blob/master/source/SuggestBoxLib/SuggestBoxBase.xaml.cs) at the `SaveRestorePopUpStateOnWindowDeActivation` method at about line 431.

Hope this helps.

**Comment by XceedBoucherS** [comment]
Hi,
The AutoCompleteBox is not a control from the Xceed WPF Toolkit.
Thank you.
