### ISSUE TITLE
DecimalUpDown not editable in VB WPF application

### ISSUE THREAD

**Issue by ClaudioGalgani** [xceedsoftware/wpftoolkit#1469]
Hi All, 

Very strange behavior from this component. 
The text is not editable, the read only properties is ignored, no events are associated;
same code works in a XAML of a C# WPF application does not work in a XAML belonging to VB WPF application (.NET Framework 4). 
I tried several ways, but nothing.. here the simple piece of code. 

<Xceed.Wpf.Toolkit:DecimalUpDown Name="sldExposure" Margin="10" Grid.Row="0" Grid.Column="1"></Xceed.Wpf.Toolkit:DecimalUpDown>

Someone knows of a bug in this kind of scenario? 
Do you have any trials to suggest?

Thanks in advance and ciao.

Claudio

**Comment by ClaudioGalgani** [comment]
I am closing the issue because any editable controls don't work in this particular Form, the issue is to look elsewhere.

Thanks.

Claudio

**Comment by XceedBoucherS** [comment]
Hi,
After testing a new Visual Basic Wpf App(.NET Framework) in VS2017, I was able to use a DecimalUpDown control and edit it :  
` <Grid>
    <xctk:DecimalUpDown Name="sldExposure"
                        Margin="10"
                        Grid.Row="0"
                        Grid.Column="1">
    </xctk:DecimalUpDown>
  </Grid>`

`Class MainWindow
    Public Sub New()
        Xceed.Wpf.Toolkit.Licenser.LicenseKey = "XXXXX-XXXXX-XXXXX-XXXX"
    End Sub
End Class`

**Comment by ClaudioGalgani** [comment]
Hello, 
Thanks for the reply! I already closed the issue and fixed the problem.
It was due to a secondary thread that wanted to refresh the UI without the Dispatcher.
Strange behavior but at certain point it was clear for me that it was not a Control problem.
Thanks and ciao. 

Claudio.
