### ISSUE TITLE
AvalonDock: Documents become invisible

### ISSUE THREAD

**Issue by dialsc** [xceedsoftware/wpftoolkit#1470]
Hi

Having an AvalonDock added to the MainWindow I open and attache documents from the code behind. In a certain situation documents opened and attached are not getting visible anymore, thus the document root pane remains empty.

1. Open and attache two documents
2. Right click the Header of one of them and select "New vertical document group"
3. Right click either one of them and select "Close all"

That's it! Opening and attaching a new document now will not be shown/visible in the LayoutDocumentPane.

Environment: Extended.Wpf.Toolkit V3.5.0 (NuGet) in Visual Studio 2017

I might just not know what I'm doing... ;) But this looks like a bug to me.

Best

dialsc

**Comment by XceedBoucherS** [comment]
Hi,
Make sure to search for an existing LayoutDocumentPane. The following works : 
` <StackPanel>
    <Button Content="Add LayoutDocument"
            Click="Button_Click" />

    <xcad:DockingManager>
      <xcad:LayoutRoot x:Name="_layoutRoot">
        <xcad:LayoutPanel x:Name="_layoutPanel">
          <xcad:LayoutDocumentPaneGroup>
            <xcad:LayoutDocumentPane>
            </xcad:LayoutDocumentPane>
          </xcad:LayoutDocumentPaneGroup>
        </xcad:LayoutPanel>
      </xcad:LayoutRoot>
    </xcad:DockingManager>
  </StackPanel>`

` private void Button_Click( object sender, RoutedEventArgs e )
    {
      var ldps = _layoutPanel.Descendents().OfType<LayoutDocumentPane>();
      if( ( ldps != null ) && ( ldps.Count() > 0 ) )
      {
        ldps.First().Children.Add( new LayoutDocument() { Title = "First", Content = new Button() { Content = "First Button" } } );
        ldps.First().Children.Add( new LayoutDocument() { Title = "Second", Content = new Button() { Content = "Second Button" } } );
      }
    }`
