### ISSUE TITLE
CollectionControlDialog.Clone() doesn't clone nested arrays and loose data

### ISSUE THREAD

**Issue by mrhelmut** [xceedsoftware/wpftoolkit#1472]
Hey there,

We're using ```PropertyGrid``` to edit our data, but we have severe issues of arrays being completely lost upon hitting the cancel button on a ```CollectionControl```.

The problem comes from ```CollectionControlDialog.Clone(object source)```, which doesn't properly clone nested lists or arrays.

If the source is a class which has an array property, ```Clone()``` results in this array being ```null``` (or sometimes only clones the first item) instead of being correctly copied. Hence, when the dialog is canceled, this array is overridden with ```null``` upon ```CollectionControl.PersistChanges( IList sourceList )``` being called.

Also note that closing a ```CollectionControl``` with the upper right close button doesn't try to restore previous data, which may be misleading.

Cheers!

**Comment by XceedBoucherS** [comment]
Hi,
this could already be fixed in latest versions. You can try the latest v3.8 version for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/.
If it's still an issue, could you send the structure of your classes with the problematic Array property ?

Thank you.
