### ISSUE TITLE
Binding to MaskedTextBox Value does not work

### ISSUE THREAD

**Issue by grinh** [xceedsoftware/wpftoolkit#1486]
Binding to MaskedTextBox Value does not work. I can Bind to Text property, however when I try to bind to Value property it does not work. I always have null.

**Comment by XceedBoucherS** [comment]
Hi,
Try adding a ValueDataType, for example : 
`ValueDataType="{x:Type s:String}" `

When all the characters are entered, the Value property will be filled.
