### ISSUE TITLE
Implement native wpf style

### ISSUE THREAD

**Issue by Shadowblitz16** [xceedsoftware/wpftoolkit#1489]
is it possible to implement the native style that the wpf app uses?
I am mainly wanting this for the ChildWindow.

**Comment by XceedBoucherS** [comment]
If you want to create a childWindow in WPF, it should be possible. PLease, have a look at Windows/ChildWindow sample from the LiveExplorer app, available here : https://xceed.com/xceed-toolkit-plus-for-wpf/
