### ISSUE TITLE
Error/Mistake within example for MessageBox

### ISSUE THREAD

**Issue by MaatkareHatschepsut** [xceedsoftware/wpftoolkit#1495]
Within the example among the according link:
https://github.com/xceedsoftware/wpftoolkit/wiki/MessageBox was a mistake. 
Because it is not `<Style TargetType="{x:Type toolkit:MessageBox}">` to get access, instead it is `<Style TargetType="{x:Type xctk:MessageBox}">`.
toolkit is not available within the version of Extended.Wpf.Toolkit 3.5.0
Also I needed to include  `xmlns:xctk="http://schemas.xceed.com/wpf/xaml/toolkit"` for it.

Maybe this could be adapted within the documentation :)

**Comment by XceedBoucherS** [comment]
Thank you.
Documentation has been updated.
