### ISSUE TITLE
AvalonDock: Restoring a layout with floating LayoutAnchorablePanes causes a NullReferenceException

### ISSUE THREAD

**Issue by Heufneutje** [xceedsoftware/wpftoolkit#1501]
When making a pane float, saving that layout and then loading the layout again a NullReferenceException occurs. I am using version 3.5.0 community edition. I have attached a sample project with which I am able to consistently reproduce the issue.

[TestDock.zip](https://github.com/xceedsoftware/wpftoolkit/files/3308337/TestDock.zip)

**Comment by Dirkster99** [comment]
I've tested your test app with the current release 3.5.7 from my branch and it does not appear to throw an exception (if you use the nuget from my branch). More likely then not I've fixed it a year ago (or so). You can see the [list of critical fixes for Avalondock 3.5 here](https://github.com/Dirkster99/AvalonDock#Mile-Stone-History).

You'll probably get a [text like this](https://github.com/xceedsoftware/wpftoolkit/issues/1448#issuecomment-478582870) as answer from this project and you'll have the choice of waiting (for months or years) or paying money if you want to stick with this project...

[TestDock_AvalonDock.zip](https://github.com/xceedsoftware/wpftoolkit/files/3309813/TestDock_AvalonDock.zip)

**Comment by Heufneutje** [comment]
Switching to your fork did indeed fix it. Thanks!
