### ISSUE TITLE
Localizing PropertyDefinition DisplayName in PropertyGrid

### ISSUE THREAD

**Issue by metal450** [xceedsoftware/wpftoolkit#1505]
I'm using a PropertyGrid in a WPF application, and attempting to localize the DisplayName of my PropertyDefinitions.  The localization method used throughout my app is this: https://www.codeproject.com/Articles/249369/Advanced-WPF-Localization

Where the XAML looks like i.e.:
<Label Content="{Loc str_Interpolation}" />

Or in the case of the PropertyGrid, I'm trying to do:
<xctk:PropertyDefinition TargetProperties="Units" DisplayName="{Loc str_DistanceUnits}"/>

However, when I switch languages, I get the exception: _Cannot modify DisplayName once the definition has beed added to a collection._.  The only reference I was able to find to this is https://stackoverflow.com/questions/29682870/extended-wpf-toolkit-propertygrid-isexpandable-template, which simply says "it shouldn't be a problem" - however, in this case, the localization doesn't take place.

Note: I'd had a discussion going about this previously, at the link https://wpftoolkit.codeplex.com/discussions/662208.  That whole forum seems to have been taken down (as far as I can tell, with no way to access the old/archived posts), so at this point I have no idea where the discussion left off.

1) How can I revisit the old discussion?
2) More importantly, is there a way to get the {Loc} code working in the PropertyGrid, as it does throughout the rest of the app?

Thanks in advance! :)

**Comment by XceedBoucherS** [comment]
Hi,

You should use another way to localize DisplayNames in the PropertyGrid.
1) Add a Resource1.resx in your project. Set its access Modifier to Public. Set property names and english values.
2) Add a Resource1.fr-FR.resx  in your project. Set its access Modifier to Public. Set property names (same as in 1)) and french values.
3) Set property attribute on your object : 
 [LocalizedDisplayNameAttribute("MyFirstName")]
    public string FirstName
    {
      get;
      set;
    }
4) Add the new class:
public class LocalizedDisplayNameAttribute : DisplayNameAttribute
  {
    private readonly string resourceName;
    public LocalizedDisplayNameAttribute( string resourceName )
        : base()
    {
      this.resourceName = resourceName;
    }

    public override string DisplayName
    {
      get
      {
        return Resource1.ResourceManager.GetString( this.resourceName );
      }
    }
  }
5) When the language is modified, update the Resource1 culture and update the PropertyGrid:
Resource1.Culture = culture;
      if( _propertyGrid != null )
      { 
          var selected = _propertyGrid.SelectedObject;
        _propertyGrid.SelectedObject = null;
        _propertyGrid.SelectedObject = selected;
      }

**Comment by metal450** [comment]
Great, thanks - will give that a try, & report back if there are any issues :)
