### ISSUE TITLE
Bug: Browsable attribute not honoured in PropertyGrid (Re-Open??)

### ISSUE THREAD

**Issue by steevcoco** [xceedsoftware/wpftoolkit#1509]
There is a closed issue, #133 that points out that public properties that have been decorated with `[Browsable(false)]` (`false`) are still being returned. I am seeing this behavior in the community edition, 3.5.0; and it very much seems like a bug.

I have implemented an object that implements `ICustomTypeDescriptor`, and some properties change the returned `BrowsableAttribute` based on the current selected object instance. The XCeed PropertyGrid IS returning my properties from the `ICustomTypeDescriptor` interface, and, the correct properties have the `[Browsable(false)]` attribute set; yet, the PropertyGrid still displays these properties.

I have found that I need to handle the PropertyGrid `IsPropertyBrowsable` event, and simply fetch the current `PropertyDescriptor` from `TypeDescriptor` (including custom descriptors), and then just set the `IsPropertyBrowsableArgs.IsBrowsable` value based on the fetched `PropertyDescriptor` attribute --- i.e. I am just setting the event to the Browsable state that IS implemented on this object by `ICustomTypeDescriptor`. The PropertyGrid will not by default honor the non-browsable Attribute even though the object is returning false; I have to handle this event in order to hide non-browsable properties.

My class implements `ICustomTypeDescriptor`, and in `GetProperties()` and `GetProperties(Attribute[])`, I am setting the `[Browsable(false)]` (`false`) on some properties dynamically based on other property values.

Stepping through the debugger confirms that the XCeed PropertyGrid IS fetching these properties, with the `[Browsable(false)]` `false`, yet the properties are still displayed.

I then handle the PropertyGrid  `IsPropertyBrowsable` event, and fetch the current `PropertyDescriptor` and just set the value on the event, and that fixed the PropertyGid display: non-browsable properties now do not show:

		private void handleIsPropertyBrowsable(object sender, IsPropertyBrowsableArgs eventArgs)
		{
			if (!((DataContext as WtPropertySetViewModel)?.PropertySet is WtPropertySet propertySet))
				return;
			eventArgs.IsBrowsable
					= ((TypeDescriptor.GetProperties(propertySet)
					.Find(eventArgs.PropertyDescriptor.Name, false)
					?? eventArgs.PropertyDescriptor)
					?.Attributes[typeof(BrowsableAttribute)] as BrowsableAttribute)
					?.Browsable;
		}

**Comment by XceedBoucherS** [comment]
Hi,
If you go in the LiveExplorer available here : https://xceed.com/xceed-toolkit-plus-for-wpf/, and aim for the sample "Data/PropertyGrid/Using SelectedObjects/Using Attributes", you will see in the "Code" tag, a property called "InvisibleProperty" with the [BrowsableAttribute(false)]. When you look at the "Sample" tag, this "InvisibleProperty" is not shown in the PropertyGrid.
If it's still not working, please paste all your code here.
Thank you

**Comment by djangohunt** [comment]
I am getting the same issue, the Browsable attribute works when used as per the xceed example, but not when set at runtime.

**Comment by XceedBoucherS** [comment]
Hi,
Please use the IsPropertyBrowsable event:
`<xctk:PropertyGrid SelectedObject="{Binding}"
                       IsPropertyBrowsable="PropertyGrid_IsPropertyBrowsable"/>`

`  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();

      this.DataContext = new Person() { FirstName = "Mike", LastName = "Jones", ID = 22 };
    }

    private void PropertyGrid_IsPropertyBrowsable( object sender, Xceed.Wpf.Toolkit.PropertyGrid.IsPropertyBrowsableArgs e )
    {
      if( e.PropertyDescriptor.DisplayName == "ID" )
      {
        e.IsBrowsable = false;
      }
    }
  }

  public class Person
  {
    public string FirstName
    {
      get;
      set;
    }

    public string LastName
    {
      get;
      set;
    }

    public int ID
    {
      get;
      set;
    }
  }`
