### ISSUE TITLE
Zoombox set viewport

### ISSUE THREAD

**Issue by thestonehead** [xceedsoftware/wpftoolkit#1510]
Hi.

I would like to save the state in which the zoombox is (namely viewport) when the application is closed and restore it when the application starts again. The problem is that there's no setter for Viewport.

Is there an alternate way to programatically set viewport of Zoombox?

**Comment by XceedBoucherS** [comment]
You can save the main values like "scale" and "position" in order to re-apply them : 

 private void Button_Click_Save( object sender, RoutedEventArgs e )
    {
      _scale = _zoombox.Scale;
      _position = _zoombox.Position;
    }

    private void Button_Click_Load( object sender, RoutedEventArgs e )
    {
      _zoombox.Scale = _scale;
      _zoombox.Position = _position;
    }
  }
