### ISSUE TITLE
IntegerUpDown: Unexpected value, when I enter a number outside the minimum-maximum-range 

### ISSUE THREAD

**Issue by mkias1983** [xceedsoftware/wpftoolkit#1515]
#### Reproduce the issue
* Define a `IntegerUpDown` control in XAML
* Set the `Minimum` value, e.g. 100
* Set the `Maximum` value, e.g. 1500
* Set the current value to a number inside the range, e.g. 700
* Run the app
* Enter a higher number than the `Maximum` or a lower number than the `Minimum` value
* Lost focus of the `IntegerUpDown` control

#### Actual behavior
* The `Value` of the `IntegerUpDown` control is set to the latest valid text value inside the range
* E.g. if you enter `1`, the value will be `700`
* E.g. if you enter `2000`, the value will be `200`

#### Expect behavior
* I expect, 
  * if I enter a higher value than the `Maximum`, the value will be the maximum
  * if I enter a lower value than the `Minimum`, the value will be the minimum

**Comment by XceedBoucherS** [comment]
Hi,
You can set the ClipValueToMinMax property to true. This will ensure the bounds will be respected.
