### ISSUE TITLE
Examples of Carousel control with Animators

### ISSUE THREAD

**Issue by ksobon** [xceedsoftware/wpftoolkit#1518]
I can't find any code samples of the Carousel Control from the WPF Plus Toolkit. The wiki here has some basic properties listed, but no actual XAML code showcasing how to setup/define Animator inputs. Can someone post some examples of what kind of Animations can be added and how to define them in XAML?

**Comment by XceedBoucherS** [comment]
Hi,
If you are talking about the Carousel from the Switch Panels controls of the Toolkit, it is part of the Plus Version. You can test them in the LiveExplorer available here https://xceed.com/xceed-toolkit-plus-for-wpf/.  Please go in section Others/SwitchPanel/Carousel of the LiveExplorer. You can look at the code that was used to create the sample with the "Code" tab of the LiveExplorer.

You can also try for free for 45 days the latest Plus version of the Toolkit at the same link.
Thank you
