### ISSUE TITLE
PropertyGrid: multiple selected objects - missing?

### ISSUE THREAD

**Issue by WrongBit** [xceedsoftware/wpftoolkit#1526]
I found only 'SelectedObject' property. I guess you cannot edit properties of multiple selected objects? It's a serious lack of functionality. Any plans to implement it?

**Comment by XceedBoucherS** [comment]
Hi, This feature  is available in the Plus version of the Toolkit.

You can use it for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/.
The Plus version is always 2-3 versions ahead, contains many more controls and features and offers fast support compare to this OpenSource version.
In bonus, you can test all the controls in the free LiveExplorer application available at the same link.
