### ISSUE TITLE
Expand/Collapse all Category of propertygrid is inactive

### ISSUE THREAD

**Issue by BuiHoaBku97** [xceedsoftware/wpftoolkit#1533]
I can't expand category by expandcategory(string) of expandallcategory. I just expand propertise. Please show me how to fix it?

**Comment by XceedBoucherS** [comment]
Hi, 
the PropertyGrid do offerd methods for expanding and/or collapsing categories, like:
-CollapseAllCategories()
-CollapseCategory( string groupName )
-ExpandAllCategories()
-ExpandCategory( string groupName )
-IsCategoryExpanded( string categoryName )
-IsCategoryCollapsed( string categoryName )
-GetCollapsedCategories()
-GetExpandedCategories()
-GetCategories()

But these are only part of the Plus version (https://xceed.com/xceed-toolkit-plus-for-wpf/).
