### ISSUE TITLE
Xceed.Wpf.AvalonDock.Themes.Expression in WPF toolkit 3.4.0

### ISSUE THREAD

**Issue by partha-srivi** [xceedsoftware/wpftoolkit#1538]
Hi,

We have been using Xceed.Wpf.AvalonDock.Themes.Expression - Expression Dark theme in Xceed.WPF.AvalonDock v 2.0.0 downloaded from http://avalondock.codeplex.com under BSD license. 

Now, we want to migrate our code to Avalondock in WPF toolkit v 3.4.0; we have found latest toolkit doesn't have Expression Dark theme. 

Is it allowed to use Xceed.Wpf.AvalonDock.Themes.Expression expression dark themes in latest AvalonDock v 3.4.0(MS Public license)? does using Xceed.Wpf.AvalonDock.Themes.Expression v 2.0.0  in AvalonDock v 3.4.0 invite any legal hassles?

I don't know this forum is the right place to raise such queries. If not, please let me know the appropriate forum or contact to clarify such issues.

Thanks,
Parthasarathy Krishnamoorthy

**Comment by XceedBoucherS** [comment]
Hi,
 Xceed.Wpf.AvalonDock.Themes.Expression - Expression Dark theme is not part of the _Xceed Toolkit_. This looks like another project on Github (https://github.com/chengming0916/AvalonDock/tree/master/Version2.0).

The _Xceed Toolkit_ from this Github site (https://github.com/xceedsoftware/wpftoolkit) now offer the latest community version at v3.6. You should use the latest version.

As displayed on the main page, here is the MS-PL license definition (https://opensource.org/licenses/MS-PL) and the summary (https://tldrlegal.com/license/microsoft-public-license-(ms-pl)) offered.

Thank you.
