### ISSUE TITLE
LayoutDocument IsSelectedChanged event

### ISSUE THREAD

**Issue by MentorEngine** [xceedsoftware/wpftoolkit#1544]
The IsSelectedChanged event fires but the values received in the event handler do not match the action of the user, and in fact seems to reflect the previously selected item. The work-around I have had to implement is to use async/await to delay for 50 milliseconds while the messages all propagate, and then the SelectedContent of the parent LayoutDocumentPane properly reflects the active tab.

**Comment by XceedBoucherS** [comment]
Hi,
If you have 2 LayoutDocuments in a LayoutDocumentPane, and each of them has a callback to IsSelectedChanged, clicking on the tab of LayoutDocument2 will result in 2 calls to IsSelectedChanged.
The first one for LayoutDocument1.IsSelected going from true to false, and the second one for LayoutDocument2.IsSelected going from false to true.
This is normal.

**Comment by MentorEngine** [comment]
I understand that this is the desired behavior, but this is not what I'm seeing. I have 3 tabs, and I do indeed get 2 calls to my event handler. Debugging those calls, the sender is the same both times, which is the currently selected tab, not the new tab. There is currently no way (in my code) to know what the new tab is, only that the active tab has changed. That's why I had to do async/await for a few ms and then I can check the active tab reliably.

Example (image pasted below). If I click on either of the other tabs, I get 2 calls from "20" into my event handler, no calls from the new tab.

![tabs](https://user-images.githubusercontent.com/46248589/68025817-cd79cf80-fc7b-11e9-82bc-7cdb39c8783b.JPG)

**Comment by XceedBoucherS** [comment]
Hi,
Can you submit your code which produces this issue ?
I have tried with Toolkit v3.6 and the sender of the IsSelectedChanged callback is never the same. Here's my code:

<xcad:DockingManager x:Name="_dockingManager">
      <xcad:LayoutRoot x:Name="_layoutRoot">
        <xcad:LayoutPanel Orientation="Horizontal">
            <xcad:LayoutDocumentPane>
              <xcad:LayoutDocument ContentId="document1"
                                   Title="Document 1"
                                   IsSelectedChanged="LayoutDocument_IsSelectedChanged">
                <Button Content="Document 1 Content"
                        HorizontalAlignment="Center"
                        VerticalAlignment="Center" />
              </xcad:LayoutDocument>
              <xcad:LayoutDocument ContentId="document2"
                                   Title="Document 2"
                                   IsSelectedChanged="LayoutDocument_IsSelectedChanged">
                <TextBox Text="Document 2 Content"
                         AcceptsReturn="True" />
              </xcad:LayoutDocument>
            <xcad:LayoutDocument ContentId="document3"
                                 Title="Document 3"
                                 IsSelectedChanged="LayoutDocument_IsSelectedChanged">
              <Button Content="Document 3 Content"
                      HorizontalAlignment="Center"
                      VerticalAlignment="Center" />
            </xcad:LayoutDocument>
          </xcad:LayoutDocumentPane>
        </xcad:LayoutPanel>

      </xcad:LayoutRoot>
    </xcad:DockingManager>

`  private void LayoutDocument_IsSelectedChanged( object sender, EventArgs e )
    {
      var layoutDocument = sender as LayoutDocument;
      if( layoutDocument != null )
      {
        System.Diagnostics.Debug.WriteLine( "layoutDocument " + layoutDocument.ContentId + ", IsSelected = " + layoutDocument.IsSelected );
      }
    } `

**Comment by MentorEngine** [comment]
Here I create the new tab and wire up the event handler.

![TabIssue](https://user-images.githubusercontent.com/46248589/68027687-fc467480-fc80-11e9-8d8c-281b99633299.JPG)

**Comment by MentorEngine** [comment]
Also, looks like I'm using AvalonDock runtime version 4.0.30319.

![AvDock](https://user-images.githubusercontent.com/46248589/68027817-59422a80-fc81-11e9-835e-99ea4e9cad53.JPG)

**Comment by MentorEngine** [comment]
And just to show you the output when I run this code and click the tabs. Each 2 values is one click.
![Tabs2](https://user-images.githubusercontent.com/46248589/68028649-5cd6b100-fc83-11e9-816c-c9a3f9db0d5a.JPG)
![outputwindow](https://user-images.githubusercontent.com/46248589/68028657-64965580-fc83-11e9-8f98-7b9e1f0f1da2.JPG)

**Comment by XceedBoucherS** [comment]
Hi,
I tried to create a sample based on yours. It still works normally. Clicking on a LayoutDocument Tab result in 2 IsSelectedChanged event, from 2 different tabs.
Here's my sample:
![1544_cs](https://user-images.githubusercontent.com/29377763/68031548-48e67b80-fc92-11e9-8767-6b47ef70be91.png)
![1544_xaml](https://user-images.githubusercontent.com/29377763/68031549-48e67b80-fc92-11e9-99b9-4fb51e805c37.png)

**Comment by MentorEngine** [comment]
In my case, if you look at "IsSelected" on the LayoutDocument, the first call comes in with IsSelected=false, then on the 2nd call it is true. So it seems like it's trying to do the correct behavior, but the document passed in on the 2nd one is the same.

I'm using the latest official binaries, not the library source, in my project. But the version matches yours.

**Comment by XceedBoucherS** [comment]
Does this happens with the latest v3.8 version of the commercial "Xceed Toolkit Plus" ? You can download it here : https://xceed.com/xceed-toolkit-plus-for-wpf/

**Comment by MentorEngine** [comment]
I don't actually have a commercial license (yet)...

**Comment by XceedBoucherS** [comment]
you can use it for free for 45 days.

**Comment by MentorEngine** [comment]
Do you have any coupon code/discount that I could apply? I own a small (as in me + 1 non-technical employee) company here in Texas...not opposed to purchasing it, and the price is reasonable, $400 is more than I can afford at the moment. I know, not the best place to ask, but GitHub doesn't allow for PMs. My email is jnagle@thrustvector.com.

**Comment by MentorEngine** [comment]
FYI...I have installed the latest xceed pro, and the problem still exists.

**Comment by XceedBoucherS** [comment]
Hi,
I believe this is something related to your precise application. 
If you start a new project add copy the code I used for my sample (earlier in this thread), do you have a normal behavior ?
I would be interested in testing your application. Can you copy its full code or create a testable project so I can test it and see what is happening ?
Thank you.

**Comment by MentorEngine** [comment]
I found the issue and indeed it was with my code. If my example had displayed the LayoutDocument title instead of the content, I would have caught it much sooner. Thanks for you help, sorry for the confusion.
