### ISSUE TITLE
PropertyGrid takes too long for adding an item to PropertyDefinitions

### ISSUE THREAD

**Issue by dularish** [xceedsoftware/wpftoolkit#1552]
In our application, a single object we bind to propertyGrid has more than 500 properties , which needs to be visualized.

At present, there is only one method `PropertyDefinitions.Add` which enables to add a property one by one. As the number of properties gets larger value, the `Add` operation gets slower and slower.

It would be better if there exists a method like `AddRange` or enabling assigning a list of PropertyDefinition objects to the property `PropertyDefinitions` or setting the size of `PropertyDefinitions` beforehand, so that `Add` method is optimized.

**Comment by XceedBoucherS** [comment]
Hi,
Your idea of using an AddRange is not bad to add properties. But first, have you considered using the ProeprtyGrid.IsVirtualizing property set to true ? Or add the properties another way ?
Can you submit your code or create a sample project so we can investigate with your code ?
Thank you.

**Comment by dularish** [comment]
Hi,

Tried setting the IsVirtualizing property to true, it unfortunately didn't make any difference.

I shall try to create a sample project soon and attach here.
