### ISSUE TITLE
AvalonDock : Unexpected behaviors during docking items

### ISSUE THREAD

**Issue by dularish** [xceedsoftware/wpftoolkit#1553]
[AvalonDockIssue.zip](https://github.com/xceedsoftware/wpftoolkit/files/3884931/AvalonDockIssue.zip)

Hello,

I have attached the solution file for reproducing the issue, and also I have attached a powerpoint presentation to reproduce the issue.

Regards,
Dularish KA

**Comment by XceedBoucherS** [comment]
Hi,
This issue is already fixed in v3.7 and up. 
I suggest you try with the latest v3.7 version available since November 26 on this site.
Thank you.
