### ISSUE TITLE
Is it possible to disable the Windows 7/8 themes from being applied automatically

### ISSUE THREAD

**Issue by jtorre39** [xceedsoftware/wpftoolkit#1556]
Hi!

Currently using the wpftoolkit's message box but its title bar seems to have the Windows 8 style theme applied to it. Is it possible to disable this theme so the standard Windows title bar is used? 

Using the nuget package version of wpftoolkit by the way!

**Comment by XceedBoucherS** [comment]
Hi,

This is the default behavior.
With the Plus version, you have access to more themes:
-Metro Light with accent Color
-Metro Dark with accent color
-Office2007 Blue
-Office2007 Black
-Office2007 Silver
-Windows 10

Thank you
