### ISSUE TITLE
Images instead of text in CheckComboBox

### ISSUE THREAD

**Issue by Vishalnandi405** [xceedsoftware/wpftoolkit#1560]
Hi!

I am trying to create a Grid View with all the columns having "CheckComboBox" in the header as filters just like the Ms Excel. 

I have a requirement where I need to change the text of one of the CheckComboBox to images. I have values like RED, YELLOW, GREEN but instead of color names I have to show images like Traffic lights of RED, YELLOW and GREEN (Roundel Images which I already have). I think it can be done with Item Template and Data Template. 

Can anyone please help me in this.

**Comment by XceedBoucherS** [comment]
Hi,

You can easily add images in the popup of the CheckComboBox. But the items selected will appear in the TextBox of the CheckComboBox. So in the following sample, the selected items will be "Light" objects.

` <Window.Resources>
    <DataTemplate x:Key="cmbTemplate">
      <WrapPanel Margin="0 5 0 5"
                 Height="80">
        <Image Width="65"
               Height="65"
               Stretch="Fill"
               Source="{Binding Color}"
               VerticalAlignment="Center"
               HorizontalAlignment="Center"
               Margin="0,0,15,0" />
        <Label Content="{Binding Name}"
               VerticalAlignment="Center"
               HorizontalAlignment="Center"
               FontSize="20" />
      </WrapPanel>
    </DataTemplate>
  </Window.Resources>
  <Grid>
    <xctk:CheckComboBox x:Name="_checkComboBox"
                        ItemsSource="{Binding Lights}"
                        ItemTemplate="{StaticResource cmbTemplate}"
                        Width="150"
                        HorizontalAlignment="Left"/>
  </Grid>`

` public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();

      this.DataContext = this;
      this.Lights = new List<Light>()
      {
        new Light() {  Name = "Red", Color = "red.png" },
        new Light() {  Name = "Yellow", Color = "yellow.png" },
        new Light() {  Name = "Green", Color = "green.png" },
      };
    }

    public List<Light> Lights
    {
      get;
      set;
    }
  }

  public class Light
  {
    public string Name
    {
      get;
      set;
    }

    public string Color
    {
      get;
      set;
    }
  }`

**Comment by Vishalnandi405** [comment]
Thanks for the help. It  works for me.
