### ISSUE TITLE
Can't use AvalonDock

### ISSUE THREAD

**Issue by Stanlyhalo** [xceedsoftware/wpftoolkit#1571]
I opened my project today, I saw the update, updated it, and now I get this error message: The name "DockingManager" does not exist in the namespace

Theirs also more errors, like in c#, I can't do "Xceed.Wpf.AvalonDock.Layout", the only available options after the "AvalonDock" part, is "Themes".

**Comment by Stanlyhalo** [comment]
Fixed all of the errors by downloading it from here. Now I get this one error: The type reference cannot find a public type named 'DockingManager'. Line 216 Position 80.

The code on that line:
<Style TargetType="xcad:DockingManager" x:Key="dckmgr_dockablewindows">

**Comment by Stanlyhalo** [comment]
fixed the errors, now I have a new problem. I'm getting an error in InitializeComponent(); that "dckmgr_dockablewindows" cannot be found as a resource name, but yet in the xaml file, their is a component that is named "dckmgr_dockablewindows" (it's a DockingManager).

**Comment by Stanlyhalo** [comment]
Solved it.

**Comment by StevenGann** [comment]
How did you solve it? I have the same issue.
