### ISSUE TITLE
when WatermarkPasswordBox get the focus, the button which set “IsDefault” = true can't work

### ISSUE THREAD

**Issue by hjj28810** [xceedsoftware/wpftoolkit#1577]
`  <TextBox
                        Name="LoginName"
                        Grid.Column="1"
                        Height="44"
                        Margin="0,10"
                        Padding="15,0"
                        FontSize="16"
                        Foreground="{DynamicResource BaseColor1}"
                        TabIndex="0"
                        TextWrapping="NoWrap"/>
                    <Border
                        Grid.Row="1"
                        Height="44"
                        Margin="0,10"
                        Background="{DynamicResource MainBackgroundC}"
                        BorderThickness="0"
                        ClipToBounds="True"
                        CornerRadius="5">
                        <toolkit:WatermarkPasswordBox
                            Padding="15,0"
                            VerticalContentAlignment="Center"
                            localUt:TextBoxHelper.BoundPassword="{Binding Password, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                            Background="{DynamicResource InputBG}"
                            BorderThickness="0" fot
                            FontSize="16"
                            Foreground="{DynamicResource BaseColor1}"
                            InputMethod.IsInputMethodSuspended="True"
                            ScrollViewer.PanningMode="None"
                            TabIndex="1"
                            Watermark="登录密码"
                            WatermarkTemplate="{StaticResource WatermarkTemplate}">
                            <toolkit:WatermarkPasswordBox.Resources>
                                <Style TargetType="ScrollViewer">
                                    <Setter Property="VerticalAlignment" Value="Center" />
                                </Style>
                            </toolkit:WatermarkPasswordBox.Resources>
                        </toolkit:WatermarkPasswordBox>
                    </Border>
 <Button
                    Name="Login"
                    Grid.Row="3"
                    Height="44"
                    Margin="0,0"
                    VerticalAlignment="Top"
                    Content="登录"
                    FontSize="17"
                    FontWeight="Regular"
                    Foreground="{DynamicResource WhiteC}"
                    IsDefault="True"
                    TabIndex="2" />`
when WatermarkPasswordBox get the focus, the button which set “IsDefault” = true can't work

**Comment by XceedBoucherS** [comment]
Hi,

This issue is already fixed for the next release : v4.0.

Until its released (weeks from now), you can test it in the Plus version(v4.0) here : https://xceed.com/xceed-toolkit-plus-for-wpf/

Thank you.
