### ISSUE TITLE
PropertyGrid change category color

### ISSUE THREAD

**Issue by nikkozp** [xceedsoftware/wpftoolkit#1586]
How can I change the color and font size of a category in PropertyGrid?

![image](https://user-images.githubusercontent.com/11537426/80863776-c8272d00-8c7e-11ea-8660-767a3eadb2b7.png)

**Comment by XceedBoucherS** [comment]
Hi,

You can use the "CategoryGroupHeaderTemplate" property of the PropertyGrid:
` <Window.Resources>
    <DataTemplate x:Key="myCategoryGroupHeaderTemplate">
      <TextBlock Text="{Binding}"
                 FontSize="20"
                 Foreground="Red" />
    </DataTemplate>
  </Window.Resources>
    <Grid>
    <xctk:PropertyGrid SelectedObject="{Binding}"
                       CategoryGroupHeaderTemplate="{StaticResource myCategoryGroupHeaderTemplate}"/>
  </Grid>`

**Comment by nikkozp** [comment]
thx
