### ISSUE TITLE
InputBinding and keyBinding doesn't work when dockable window state is floating.

### ISSUE THREAD

**Issue by Jinten** [xceedsoftware/wpftoolkit#1592]
My english is not well, sorry.  

KeyBinding and InputBinding work only for MainWindow.

If dockable window is activated, MainWindow InputBinding and KeyBinding will work. But it is OK, I can control even if like that behavior. (Actually, I want KeyBinding to work on dockable window declarated.)

Problem is that doesn't work when DockableWindow is floating.
If key down on the floating dockable window, event triggered just only LayoutDocumentFloatingWindowControl.
![CalledJustOnlyLayoutDocumentFloatingWindowControl](https://user-images.githubusercontent.com/9315925/82723022-7cf4bd00-9d06-11ea-8751-d023825fd81e.PNG)

I declarated InputBinding and KeyBinding on the xaml of dockable window. (My UserControl.xaml)
But it doesn't work...Can I detect key down on the floating dockable window?
If it is possible, How should I implement?
I most want way of implement is to be work just declare InputBinding and KeyBinding on the dockable view xaml.

This is the small sample project.
[sample.zip](https://github.com/xceedsoftware/wpftoolkit/files/4671286/sample.zip)

Output string as "Called from InputBinding on MainWindow." at console when Ctrl+S keys down.
How to confirm the problem.
1. Click the CreateTestView button.
![CreateTestView](https://user-images.githubusercontent.com/9315925/82723233-63547500-9d08-11ea-925e-f8f03cc34716.PNG)
2. Drag created the test view tab.
(If Ctrl+S keys down at here, output string as same above sentence. But it's okay this behavior)
![dragging](https://user-images.githubusercontent.com/9315925/82723256-a6164d00-9d08-11ea-9c3a-4dd6bea7dcf0.PNG)
3. Ctrl+S keys down on the TestView. (dockable window).
Expected work is output string as "Called from InputBinding on TestViewModel."
But it doesn't work as Expected.

Thank you for checking this issue.

**Comment by XceedBoucherS** [comment]
Hi,

The TestView only contains a TextBlock which can't be selected. Try using another selectable control, like a TextBox and make sure it gets the focus once you click in the TestView (floatingWindow). When this is the case, you will see your output.

**Comment by Jinten** [comment]
Thank you for teaching me that knowledge.
I could solve the problem as you said.
I appreciate your help.
I'm going to close this Issue.
