### ISSUE TITLE
NumericUpdown width

### ISSUE THREAD

**Issue by MichalNekvasil** [xceedsoftware/wpftoolkit#1593]
Hello there, I have a problem. See a pic

![image](https://user-images.githubusercontent.com/16255036/84010219-a8b5ab00-a974-11ea-9b5c-05afd3037c09.png)

NumericUpdDown is not wide enough to fit content .... how can I fix this?

Thanks
MN

**Comment by XceedBoucherS** [comment]
Hi,
I believe you are using the ColorPicker control, which contains (in the advanced tab) a ColorCanvas.
In the ColorCanvas, it's not NumericUpDowns but ByteUpDowns controls that are used.
If you try the LiveExplorer app, in sample "input Fields/Color", we can not reproduce this kind of bug.
How do you end up with a smaller popup ?
Thank you.

**Comment by MichalNekvasil** [comment]
Hi and thanks for quick response. When I know it's ByteUpDown control, I
just hide ButtonSpinner in style. Anyway it looks nicer and cleaner without
these buttons.

Thank you and have a nice day.
M. Nekvasil

po 8. 6. 2020 v 14:58 odesílatel XceedBoucherS <notifications@github.com>
napsal:
