### ISSUE TITLE
XAML compilation error with attached properties

### ISSUE THREAD

**Issue by hhfranzo** [xceedsoftware/wpftoolkit#1601]
Hi,

I'm trying to migrate a .NET application that is using AvalonDock 2.0 to 4.0. 
In the XAML in the DockingManager I have a DataTemplateSelector element that is defined as an attached property in an external static class. 
Here a simple snippet that shows the XAML:

<Window x:Class="DockingManagerAttachedProperty.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:DockingManagerAttachedProperty" 
        xmlns:xcad="http://schemas.xceed.com/wpf/xaml/avalondock"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Window.DataContext>
        <local:AchorableSourceViewModel/>
    </Window.DataContext>
    <Grid>
        <xcad:DockingManager local:AttachedPropertyProvider.AnchorablesSource="{Binding Items}" >
            <local:AttachedPropertyProvider.AnchorableTemplateSelector>
                <DataTemplateSelector></DataTemplateSelector>
            </local:AttachedPropertyProvider.AnchorableTemplateSelector>
        </xcad:DockingManager>
    </Grid>
</Window>

The code compiles and runs with AvalonDock 2.0 while with latest version I'm getting the following compilation error:

**Parent element or property 'DockingManager' requires an XML data island. To distinguish an XML island from surrounding XAML, wrap the XML data island in <x:XData> ... </x:XData>. Line 15 Position 14.**

Attached you find a very simple code example that demonstrates the issue.

Cheers,
M.

[DockingManagerAttachedProperty.zip](https://github.com/xceedsoftware/wpftoolkit/files/5002122/DockingManagerAttachedProperty.zip)

**Comment by XceedBoucherS** [comment]
Hi,
Not sure why, but try using the AnchorableTemplateSelector attached property as a one-liner, using a resource key object:
[1601.txt](https://github.com/xceedsoftware/wpftoolkit/files/5125343/1601.txt)

**Comment by hhfranzo** [comment]
It works! 

Thanks,
M.
