### ISSUE TITLE
Understanding v4.0 Free vs. Plus and the future of .NET Core 3

### ISSUE THREAD

**Issue by jtblsngm** [xceedsoftware/wpftoolkit#1604]
I understand that **Plus Edition** releases with new content and bug fixes sooner than the free, community-licensed version. I also understand the **Plus Edition** has features completely missing from the free, community version.

On January 30, 2020 v.4.0.0 was released for registered **Plus Edition** users. It had this patch note:

> - All controls from the Toolkit are now available for the .NET Core 3 platform.

On June 26, 2020 v4.0.0 was released free, to the community, but with no patch note regarding the .NET Core 3 platform.

This is what is listed under the **feature comparison page**. The first column is the free, community version. 

> ![confusion](https://user-images.githubusercontent.com/20510809/90193624-f42c7100-dd8a-11ea-9f39-09ee8133087f.png)

Am I right that the convenience and power of Extended.Wpf.Toolkit is not coming to .NET Core 3 for the free, community-licensed version now, or in the future?

Thanks, and here's to hoping for some good news!
`\jtb`

**Comment by XceedBoucherS** [comment]
Hi @jtblsngm ,
You have seen right, the Extended.Wpf.Toolkit is not coming to .NET Core 3 and up  for the free, community-licensed version.
It is not planned for now. If you need the toolkit under .NET Core 3 and up, please try the Plus Edition, where a free 45 days trial is available here : https://xceed.com/en/our-products/product/toolkit-plus-for-wpf/
Thank you

**Comment by jblsngm** [comment]
Thank you. I appreciate the clarification. 👍 
`\jtb`
