### ISSUE TITLE
Please tell me how to use DoubleUpDown to show the comma as decimal symbol

### ISSUE THREAD

**Issue by Hong67890** [xceedsoftware/wpftoolkit#1610]
Please tell me how to use DoubleUpDown to show the comma as decimal symbol. I have two options for decimal, one is period used in US, and another one is comma used for some other countries. 
Using
 
CultureInfo cultureFr = new CultureInfo("fr-FR");
value = double.Parse(value).ToString(cultureFr);

to convert period to comma, but in the end, it is not showing comma symbol by using DoubleUpdown. For example, if the initial value is “15.5”, after above conversion, the value should be “15,5”. However, after running the program, the final value shown on the DoubleUpdown box is something like “155” or still “15.5”. 
Missing some settings on xmal or something is wrong in the conversion code?

**Comment by XceedBoucherS** [comment]
Hi,
Simply use the CultureInfo property:
`<StackPanel>
    <xctk:DoubleUpDown Value="15.5"
                       CultureInfo="fr-FR"/>
    <xctk:DoubleUpDown Value="15.5"
                       CultureInfo="en-US" />
  </StackPanel>`
