### ISSUE TITLE
The MaskedTextBox control's IsMaskCompleted returns false, when fetching data from the database

### ISSUE THREAD

**Issue by Rod-in-NM** [xceedsoftware/wpftoolkit#1611]
I am using MultiBinding on a border control, which has a MaskedTextBox within it. The converter I'm using combines the IsMaskCompleted and a custom bool property in the VM called IsTargetCompleted. I've found that when the user control I'm working with produces data from the database and that data would normally make the IsMaskCompleted true, it instead returns false. Here's the relevant XAML:

```XAML
<Border Grid.Row="1" 
		Grid.Column="1">
	<Border.BorderThickness>
		<MultiBinding Converter="{StaticResource multiBoolToThicknessConverter}">
			<Binding ElementName="TargetMaskedTextBox, Path=IsMaskCompleted" />
			<Binding Path="IsTargetCompleted" />
		</MultiBinding>
	</Border.BorderThickness>
	<tk:MaskedTextBox x:Name="TargetMaskedTextBox"
					  Style="{StaticResource LeftAlignMaskedTextBoxStyle}"
					  Value="{Binding Target}"
					  IsEnabled="{Binding IsTargetEnabled}"
					  ValueDataType="{x:Type System:Single}"
					  Mask="\0.0##" />
</Border>
```
Here's the Convert method from the converter I wrote:

```csharp
public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
{
	try
	{
		bool? boolOneNullable = values[0] as bool?;
		bool? boolTwoNullable = values[1] as bool?;

		bool boolOne = true;
		bool boolTwo = true;

		if (!boolOneNullable.HasValue)
		{
			boolOne = false;
		}
		else
		{
			boolOne = boolOneNullable.Value;
		}

		if (!boolTwoNullable.HasValue)
		{
			boolTwo = false;
		}
		else
		{
			boolTwo = boolTwoNullable.Value;
		}

		var combinedBools =  boolOne && boolTwo;

		if (combinedBools)
		{
			return new Thickness(0);
		}
		else
		{
			return new Thickness(1);
		}

	}
	catch (Exception)
	{
		return null;
	}
}
```
I'm using version 4.0.1 of the Extended.Wpf.Toolkit.

**Comment by XceedBoucherS** [comment]
Hi,
In XAML, make sure your Binding works. Based on your code snipet, I modified
Binding ElementName="TargetMaskedTextBox, Path=IsMaskCompleted"
to
Binding ElementName="TargetMaskedTextBox" Path="IsMaskCompleted" 
and it worked (check the quotes).

**Comment by Rod-in-NM** [comment]
Thank you, @XceedBoucherS, for your reply. I am using the `Binding ElementName="TargetMaskedTextBox, Path=IsMaskCompleted"` format because that's what agrees with Microsoft's documentation: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.binding.elementname?view=winrt-18362

**Comment by XceedBoucherS** [comment]
Yes, but in the reference link, it shows : 
`<TextBox Text="{Binding ElementName=slider1, Path=Value, Mode=TwoWay}"/>` 
where the Text equals to a complete binding.
In your sample, you say : 
`<Binding ElementName="TargetMaskedTextBox, Path=IsMaskCompleted" />`
 where you are defining a binding and its specific properties (which is why each property value should have its own quotes and be written as 
`<Binding ElementName="TargetMaskedTextBox, Path=IsMaskCompleted") />`.

**Comment by Rod-in-NM** [comment]
Thank  you, @XceedBoucherS
