### ISSUE TITLE
PropertyGrid change table color

### ISSUE THREAD

**Issue by maoyao-on** [xceedsoftware/wpftoolkit#1620]
How can I change the color of a category in PropertyGrid?
<img width="117" alt="query" src="https://user-images.githubusercontent.com/69897797/95004676-0c996900-0621-11eb-9b28-4cf13178fc4e.png">

**Comment by XceedBoucherS** [comment]
Hi,

Based on your snapshot:
-the right red rectangle: you can modify the PropertyItem Background:
`<Window.Resources>
    <Style TargetType="{x:Type xctk:PropertyItem}">
      <Setter Property="Background"
              Value="Orange" />
    </Style>
  </Window.Resources>`

-the left red rectangle: This is currently an hardcoded value in Xceed.Wpf.Toolkit/PropertyGrid/Themes/Aero2.NormalColor.xaml, 
in style with key "ExpanderStyle", there is a border with:
Background="{x:Static SystemColors.ControlBrush}" 
which you can change.
In v4.1, you will be able to modify this color easily with:
`<SolidColorBrush x:Key="{x:Static SystemColors.ControlBrushKey}"
                         Color="Red" />`
