### ISSUE TITLE
PropertyGrid: Making properties expandable without attributes

### ISSUE THREAD

**Issue by mstefarov** [xceedsoftware/wpftoolkit#1621]
Hi! I am using PropertyGrid to display objects that come from a third-party library. I have no way to put attributes on those classes, since I don't control that source code. Short of wrapping everything in ViewModels, is there any way for me to make certain properties expandable on these objects?

**Comment by XceedBoucherS** [comment]
Hi,

If you use the Plus version of the Toolkit, available here (https://xceed.com/en/our-products/product/toolkit-plus-for-wpf), you will have access to a new event on the PropertyGrid: IsPropertyExpandable.

If you register to this event, in the handler you will have the possibility to set the IsExpandable property. 
` _propertyGrid.IsPropertyExpandable += this._propertyGrid_IsPropertyExpandable;`
` private void _propertyGrid_IsPropertyExpandable( object sender, Toolkit.PropertyGrid.IsPropertyExpandableArgs e )
    {
      if( e.PropertyDescriptor.DisplayName == "Spouse" )
      {
        e.IsExpandable = true;
      }
    }`

You can try the Plus version for free for 45 days.
Thank you.

**Comment by mstefarov** [comment]
Thanks, that answers my question 👍
