### ISSUE TITLE
Error XDG0040	 The Property “inlineXml” can only be set once occurred in x64 platform

### ISSUE THREAD

**Issue by Dorthyn** [xceedsoftware/wpftoolkit#1623]
Hi,
I've put LayoutAnchorable**s** into a same **LayoutAnchorablePane**. Everything goes well when I set the target platform as **AnyCPU** or **x86**, but when I switch the platform to **x64** and rebuild the project, the error "**XDG0040	 The Property _inlineXml_ can only be set once**" occurred.
However it can still be built successfully and run and seems normal except the XAML designer cannot work as expected.
What's wrong with the problem? Is this a bug or is there something I am missing? Related codes post here. The version is 4.0.20417.14530. Any help would be appreciated.

```xml
<avalonDock:DockingManager x:Name="DockingManager">
        <avalonDock:LayoutRoot>
            <avalonDock:LayoutPanel x:Name="MainPanel" Orientation="Horizontal">
                <avalonDock:LayoutAnchorablePaneGroup DockWidth="300" Orientation="Vertical">
                    <avalonDock:LayoutAnchorablePane >
                        <!--here is the first node-->
                        <avalonDock:LayoutAnchorable Title="First" CanClose="False" CanHide="False">
                            <Canvas Background="LightGray"/>
                        </avalonDock:LayoutAnchorable>
                        <!--and here is the second node-->
                        <avalonDock:LayoutAnchorable Title="Second" CanClose="False" CanHide="False">
                            <Canvas Background="LightGray"/>
                        </avalonDock:LayoutAnchorable>
                    </avalonDock:LayoutAnchorablePane>
                </avalonDock:LayoutAnchorablePaneGroup>
            </avalonDock:LayoutPanel>
        </avalonDock:LayoutRoot>
    </avalonDock:DockingManager>
```

**Comment by XceedBoucherS** [comment]
Maybe you can have a look at answer from here : https://stackoverflow.com/questions/5378919/visual-studio-designer-in-x64-doesnt-work

**Comment by Dorthyn** [comment]
Thanks for your reply.
