### ISSUE TITLE
ChildWindow's titlebar does not look like MainWindow's titlebar

### ISSUE THREAD

**Issue by Shadowblitz16** [xceedsoftware/wpftoolkit#1632]
ChildWindow's titlebar does not look like MainWindow's titlebar by default.

![image](https://user-images.githubusercontent.com/2453707/103491242-f3968480-4dd6-11eb-9695-a9fe26814688.png)

**Comment by XceedBoucherS** [comment]
Hi,
You can always set the WindowBackground property to any color to modify the header background and set the BorderThickness to adjust the inside borders. 
When not set, the default header background value:  
<SolidColorBrush x:Key="Window_WindowBackground" Color="{x:Static media:WindowColors.ColorizationColor}" />,
 which is explained here : https://doc.xceed.com/xceed-toolkit-plus-for-wpf/Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.Core.Media.WindowColors~ColorizationColor.html.

**Comment by Shadowblitz16** [comment]
Why doesn't it use the same themes as the main window titlebar?

**Comment by XceedBoucherS** [comment]
Yes, this is already fixed. The fix will be included in v4.2.
Thank you.
