### ISSUE TITLE
ColorCanvas foreground 

### ISSUE THREAD

**Issue by LostLeqend** [xceedsoftware/wpftoolkit#1634]
I had some troubles with the Foreground on the ColorCanvas.
I did set the Foreground on the Color Canvas but it does not get used. The TextBoxLineDrawing Visual within the TextBox has its own Value. Any Styles or other Attempts to reach a change of the Foreground did not work.

![image](https://user-images.githubusercontent.com/54739424/103986249-b5a8b000-518a-11eb-99bb-26cabd9d3b56.png)
![image](https://user-images.githubusercontent.com/54739424/103986272-bd685480-518a-11eb-8987-67fe6fb95fff.png)

**Comment by XceedBoucherS** [comment]
Hi,
Using Toolkit v4.0.2 from NuGet and using a ColorCanvas with a Red Foreground results in this:
![image](https://user-images.githubusercontent.com/29377763/104062429-7c8f3080-51c8-11eb-892b-27dbc1b8cd13.png)
All allpha-numeric values have a red foreground.

Which TextBox are you trying to modify ?
Thank you.

**Comment by LostLeqend** [comment]
I was doing the same thing and it didn't work. Im not sure which version we are using but that's the problem then. Thank you!
