### ISSUE TITLE
Documentation mistake: MaskedTextBox

### ISSUE THREAD

**Issue by MikeFarrington** [xceedsoftware/wpftoolkit#1639]
https://github.com/xceedsoftware/wpftoolkit/wiki/MaskedTextBox

The description for the Masking Element characters "A" and "a" are identical though their functions differ.  "A"'s descriptiong should start with "Alphanumeric, **_required_**." not "Alphanumeric, ~~optional~~."

![image](https://user-images.githubusercontent.com/40607634/105252241-16e95f80-5b4b-11eb-906a-07cb3fbce9cc.png)

**Comment by XceedBoucherS** [comment]
Hi,
Thank you for pointing this out.
The documentation page is now fixed.
