### ISSUE TITLE
AvalonDock NuGet package with .NET Core

### ISSUE THREAD

**Issue by Cubey2019** [xceedsoftware/wpftoolkit#1648]
Using the latest AvalonDock package (4.1.21063.2360), the build fails for .NET Core.

**error MC3074: The tag 'DockingManager' does not exist in XML namespace 'http://schemas.xceed.com/wpf/xaml/avalondock'. Line 24 Position 10.**

```xml
<PackageReference Include="Xceed.Products.Wpf.Toolkit.AvalonDock" Version="4.1.21063.2360" />
```

In my XAML file I just have:
```xaml
<Window x:Class="XceedCore.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:xctk="http://schemas.xceed.com/wpf/xaml/toolkit"
        xmlns:xcad="http://schemas.xceed.com/wpf/xaml/avalondock"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition />
        </Grid.RowDefinitions>

        <xctk:WatermarkTextBox Watermark="Enter text here please." />
        <xcad:DockingManager Grid.Row="1" />
    </Grid>
</Window>
```

The problem appears to be in the nuspec file for the AvalonDock package where there is a `<references>` tag that I believe forces NuGet to reference the .NET Framework DLL:
```xml
    <references>
      <reference file="Xceed.Wpf.AvalonDock.dll" />
    </references>
```

**Comment by XceedBoucherS** [comment]
Hi,
Thank you for reporting this.

This issue is fixed and should have been fixed on NuGet too.
Probably a wrong package uploaded on NuGet.
We will look into this to fix it ASAP.
Thank you.

**Comment by Cubey2019** [comment]
I've updated to the new package version (4.1.21122.16390) and the build works now.

Thanks for fixing this quickly.
