### ISSUE TITLE
Scroll in ColorPicker

### ISSUE THREAD

**Issue by balkarov** [xceedsoftware/wpftoolkit#1657]
If ColorPicker has many colors then some colors are not visible.
![Безымянный](https://user-images.githubusercontent.com/6030335/114385865-2fd93e00-9b99-11eb-9aa4-08892d57d04c.png)

**Comment by XceedBoucherS** [comment]
Hi,

You could try to go in file 
-Xceed.Wpf.Toolkit/ColorPicker/Themes/Aero2.NormalColor.xaml (for Windows 8 and up)
-Xceed.Wpf.Toolkit/ColorPicker/Themes/Generic.xaml (for other Windows)

and look for Style "ColorListStyle" and modify the MaxHeight from 500 to 275 (which is about 13-14 lines of colors). This way, a scrollbar should appear if you have a List of colors greater than 275 in height.
