### ISSUE TITLE
TimePicker starting time not setting correctly

### ISSUE THREAD

**Issue by Omcsesz** [xceedsoftware/wpftoolkit#1658]
Hello, Team!

When I'm using two columns in a DataGrid, both of them containing a Timepicker when editing them, one contains the start time I set, but the other contains 23:59 instead (see attached VS project).

Am I missing something trivial?

[TestProject_.zip](https://github.com/xceedsoftware/wpftoolkit/files/6329973/TestProject_.zip)

**Comment by XceedBoucherS** [comment]
Hi,
TimePicker.Value is of type DateTime while TimePicker.StartTime/EndTime are of type TimeSpan.
In your sample, you bind to MyTableRow.StartTime/EndTime which are of type string.
You can not bind properties of type string with properties of type TimeSpan.
Also, your TextBoxes for StartTime/EndTime are binding their Text property (of type string) with TimePicker.StartTime/EndTime (of type TimeSpan).

Here's the modification of your xaml for the StartTime:
` <DataGridTemplateColumn.CellEditingTemplate>
            <DataTemplate>
              <StackPanel>
                
                <xctk:TimePicker x:Name="dp"
                                 Value="{Binding StartTime, Converter={StaticResource MyConverter}}"
                                 Visibility="Collapsed"
                                 StartTime="{Binding StartTime, Converter={StaticResource MyConverter}}" />
                
                <TextBox Text="{Binding Text, ElementName=dp}"
                         Name="StartTimeTextBox"
                         PreviewKeyDown="StartTimeTextBox_PreviewKeyDown"
                         PreviewTextInput="StartTimeTextBox_PreviewTextInput" />
              </StackPanel>
            </DataTemplate>
          </DataGridTemplateColumn.CellEditingTemplate>`

I'm using a converter to manage the binding conversion of strings to TimeSpan:
` public class MyConverter : System.Windows.Data.IValueConverter
  {
    public object Convert( object value, Type targetType, object parameter, CultureInfo culture )
    {
      if( ( value is string ) && string.IsNullOrEmpty( value as string ) )
        return DateTime.Now;
    
      ......

      return value;
    }

    public object ConvertBack( object value, Type targetType, object parameter, CultureInfo culture )
    {
      throw new NotImplementedException();
    }
  }`

**Comment by Omcsesz** [comment]
I understand, but why does one of the columns display it correctly, and the other does not?

**Comment by XceedBoucherS** [comment]
Just make sure the Converter does the correct thing. After fixing the binding, I was able to have valid values in both columns.

**Comment by Omcsesz** [comment]
I bound the MyConverter class as you mentioned, but I get an Exception when I try to edit the StartTime column. I attach the modified testproject.
[TestProject_.zip](https://github.com/xceedsoftware/wpftoolkit/files/6344726/TestProject_.zip)

**Comment by Omcsesz** [comment]
![image](https://user-images.githubusercontent.com/1839739/115537486-23409e00-a29b-11eb-9554-28a6c4177474.png)

**Comment by XceedBoucherS** [comment]
Hi,

you need to defined the Resource MyConverter in XAML with a key:

`xmlns:local="clr-namespace:TestProject"
<Window.Resources>
    <local:MyConverter x:Key="MyConverter" />
  </Window.Resources>`

**Comment by Omcsesz** [comment]
This solved the exception, but now I get a different one after I edited the value:
System.NotImplementedException: 'The method or operation is not implemented.'

**Comment by XceedBoucherS** [comment]
Hi,

You have to implement the ConvertBack method to convert from DateTime to string:
` object IValueConverter.ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
          if( value is DateTime )
          {
           ( (DateTime)value ).ToString();
          }
           return null;
        }`

**Comment by Omcsesz** [comment]
> 
> 
> Hi,
> 
> You have to implement the ConvertBack method to convert from DateTime to string:
> ` object IValueConverter.ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) { if( value is DateTime ) { ( (DateTime)value ).ToString(); } return null; }`

I'm sorry, but this solution does not work. If I use the code you provided, after editing the cells content, I get an empty cell (see attached GIF).

When I try to edit that cell, I get an error:
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' BindingExpression:Path=StartTime; DataItem='MyTableRow' (HashCode=48433347); target element is 'TimePicker' (Name='dp'); target property is 'StartTime' (type 'TimeSpan')
[TestProject_.zip](https://github.com/xceedsoftware/wpftoolkit/files/6361108/TestProject_.zip)
[NoCellContentVisibleAfterEditing.gif](https://user-images.githubusercontent.com/1839739/115782672-3ac37800-a3bc-11eb-90c9-46abda04c234.gif)

**Comment by Omcsesz** [comment]
Any ideas?

**Comment by Omcsesz** [comment]
Hello!

I found the solution. The problem was that the databinding in the StackPanel was like so:
`<TextBox Text="{Binding StartTime,  ElementName=dp2}"`
instead of 
`<TextBox Text="{Binding Text, ElementName=dp2}"`
