### ISSUE TITLE
The Text property of CheckComboBox cannot be Binding correctly

### ISSUE THREAD

**Issue by CodingOctocat** [xceedsoftware/wpftoolkit#1688]
Although `CheckComboBox` has `DisplayMemberPath` property and it is displayed in `Text` property synchronously, I need to display different `Path` on `Text` and I tried to bind it manually, but it didn't work.

```XAML
<xctk:CheckComboBox Delimiter=" "
                    DisplayMemberPath="Description"
                    IsEditable="True"
                    ItemsSource="{Binding ScopeItems}"
                    Text="{Binding ScopeString, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}">
</xctk:CheckComboBox>
```
``` CSharp
public class ScopeItem
{
    public string Description { get; set; }
    public string Scope { get; set; }
}

// Code-Behind("NotifyPropertyChanged" has been implemented)：
public string ScopeString { get; set; } => ...;
```

**Comment by XceedBoucherS** [comment]
Hi,
I'm not sure what you want to display in the Text of the CheckComboBox, but you can always create your own CheckListBox and override the UpdateText() method:
`public class MyCheckComboBox : CheckComboBox
  {
    protected override void UpdateText()
    {
      this.SetCurrentValue( CheckComboBox.TextProperty, "ABC" );
    }
  }`
instead of binding the CheckComboBox.Text to something else.
