### ISSUE TITLE
How do I get the one of the exact control after all property controls are generated?

### ISSUE THREAD

**Issue by cdytoby** [xceedsoftware/wpftoolkit#1700]
For example, I want to get the second ComboBox in the list, and I want to do something to it, like changing the available items. How do I access it after all controls are generated?

**Comment by cdytoby** [comment]
OK I solved it by using the property "propertyGrid.Properties", it is type IList and no documentation mentions this IList is a list of type "PropertyItem", from there I can access "PropertyName" and "Editor", and the "Editor" is the actual control of that property.

I hope you can document it with these detail.

**Comment by XceedBoucherS** [comment]
Hello.
for PropertyGrid.Properties, the documentation says :
 Gets the current collection of generated PropertyItem instances.
https://doc.xceed.com/xceed-toolkit-plus-for-wpf/webframe.html#Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.PropertyGrid.PropertyGrid~Properties.html

So we know we will have PropertyItem. 

What more details would you expect ?
Thank you.

**Comment by cdytoby** [comment]
Sorry, I didn't realize there is an extra documentation exist. How do I access it?

I only checked https://github.com/xceedsoftware/wpftoolkit/wiki/PropertyGrid this page, and the Properties in the table says:

"Gets the current collection of generated PropertyItems."

I didn't realize PropertyItems is a type "PropertyItem", also I didn't realize there I can access Editor.

Also, how do I access the page https://doc.xceed.com/xceed-toolkit-plus-for-wpf/webframe.html from this GitHub page? I don't know that it exists.

**Comment by XceedBoucherS** [comment]
Ok sorry,
I gave you the link for the documentation of the commercial version of Xceed Toolkit. 

On GitHub, you have the free version of Xceed Toolkit, with a smaller documentation. 
The commercial version is the free version + some new features and new controls. The commercial product documentation is still  valid when you use the free version.

On GitHub, you have more details about the commercial version here : https://github.com/xceedsoftware/wpftoolkit/wiki/Xceed-Toolkit-Plus-for-WPF

I can modify the definition of PropertyGrid.PropertyItems with the one from the commercial version.
Thank you.
