### ISSUE TITLE
Change the Font on the Material Tab

### ISSUE THREAD

**Issue by ZionGates** [xceedsoftware/wpftoolkit#1702]
Greetings, I'm using the MaterialTabControl and I like the cool animations however I can't seem to find the setting to change the Font on the Tabs themselves (where you click to change the tab page). Please assist.

**Comment by ZionGates** [comment]
Also can the tabs be aligned to the Center instead of being left aligned?

**Comment by XceedBoucherS** [comment]
Hello,
To change the font Color on the MaterialTabItems, simply set a Foreground on each of them:
<xctk:MaterialTabItem Header="First"
                                        HorizontalContentAlignment="Center"
                                        Content="MaterialTabItem #1" 
                                        Foreground="Green"/>

Or set a style from the MaterialTabControl:
 <xctk:MaterialTabControl x:Name="materialTabControl"
                                        TabStripPlacement="Top"
                                        IsInkEffectActive="True"
                                        IsInkBarActive="True"
                                        IsSlidingAnimationActive="True">
            <xctk:MaterialTabControl.Resources>
              <Style TargetType="{x:Type xctk:MaterialTabItem}">
                <Setter Property="Foreground"
                        Value="HotPink" />
              </Style>
            </xctk:MaterialTabControl.Resources>
 </xctk:MaterialTabControl >

For MaterialTabItem alignment, the tabs are always aligned to left, just like a standard TabControl with its TabItems aligned to left.

**Comment by XceedBoucherS** [comment]
Hi,
To modify the FontFamily instead of the Foreground, just replace the Foreground with FontFamily in the preceding example.

To do it in code-behind, you can do the same:
-For all the MaterialTabItems:
var myStyle = new Style( typeof( MaterialTabItem ) );
      myStyle.Setters.Add( new Setter( FontFamilyProperty, new FontFamily("Wingdings") ) );
      materialTabControl.Resources.Add( typeof( MaterialTabItem ), myStyle );

-For a specific MaterialTabItem:
_materialTabItem.FontFamily = new FontFamily( "Wingdings" );

Thank you

**Comment by ZionGates** [comment]
> Hi, To modify the FontFamily instead of the Foreground, just replace the Foreground with FontFamily in the preceding example.
> 
> To do it in code-behind, you can do the same: -For all the MaterialTabItems: var myStyle = new Style( typeof( MaterialTabItem ) ); myStyle.Setters.Add( new Setter( FontFamilyProperty, new FontFamily("Wingdings") ) ); materialTabControl.Resources.Add( typeof( MaterialTabItem ), myStyle );
> 
> -For a specific MaterialTabItem: _materialTabItem.FontFamily = new FontFamily( "Wingdings" );
> 
> Thank you

Thanks, that helped me.
