### ISSUE TITLE
net5.0-windows7.0, net6.0-windows7.0 target

### ISSUE THREAD

**Issue by tqk2811** [xceedsoftware/wpftoolkit#1708]
Can this project upgrade for net5.0-windows7.0, net6.0-windows7.0 (or some target net5 and 6 can use on nuget)
I believe the future will definitely have to go up

**Comment by XceedBoucherS** [comment]
Hello,
Yes, this is already available in the Plus version of the Toolkit. This version offers .NET5(which also works in a .NET6 environment) and  .NETCore dlls.
You can try it for free for 45 days here : https://xceed.com/en/our-products/product/toolkit-plus-for-wpf

The open source version of the Toolkit should eventually offer those versions. But for now it only offers a .NET Framework version.
