### ISSUE TITLE
xctk:ColorPicker localization

### ISSUE THREAD

**Issue by QilongTang** [xceedsoftware/wpftoolkit#1720]
Is localization implemented for it?
I tried to use the following code during initialization to set it to a different language but there seems to be no effect
```
Language = XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag);
```

Any help is appreciated!

**Comment by XceedBoucherS** [comment]
Hi,
In ColorPicker, you have a few properties, ending by "Header" which let you specify the text you want to display for these specific words: AdvancedTabHeader, AvailableColorsHeader, RecentColorsHeader, StandardTabHeader, StandardColorsHeader

Thank you

**Comment by QilongTang** [comment]
@XceedBoucherS Thank you for the help! I will close this.
