### ISSUE TITLE
Issues Updating to 4.4 on .net 6

### ISSUE THREAD

**Issue by pvoelker** [xceedsoftware/wpftoolkit#1722]
I've updated my project from 4.3 to 4.4 on a .net 6 WPF project.  Did namespaces change?  I'm getting build errors now.  Here is an example:

`xmlns:tk="clr-namespace:Xceed.Wpf.Toolkit;assembly=Xceed.Wpf.Toolkit"`

`<tk:IntegerUpDown Grid.Column="4" Value="{Binding Path=RemotePort}" Width="75" Minimum="0" Maximum="65535" IsEnabled="{Binding Path=EnabledRemote}"/>`

I get the build error:  `Error	XDG0008	The name "IntegerUpDown" does not exist in the namespace "clr-namespace:Xceed.Wpf.Toolkit;assembly=Xceed.Wpf.Toolkit".	DMXForGamers`

Here are my main project settings:
```
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
```

**Comment by XceedBoucherS** [comment]
Hello,
Try by replacing your "xmlns" with:
xmlns:tk="http://schemas.xceed.com/wpf/xaml/toolkit"
or
xmlns:tk="clr-namespace:Xceed.Wpf.Toolkit;assembly=Xceed.Wpf.Toolkit.NET5"

The NET5 assembly must be used for .NET5/6 applications.

Thank you

**Comment by pvoelker** [comment]
That worked, thank you for your help
