### ISSUE TITLE
CheckListBox. How change language "Select All" 

### ISSUE THREAD

**Issue by Andrey-2021** [xceedsoftware/wpftoolkit#1725]
Hi!

I want change  string "Select All" 
to another language.
How I can do it?

Thanks.

**Comment by zhongruijia** [comment]
这里是郭瑞的邮箱，已收到您的来件，我会尽快拜阅并给予您回复

**Comment by XceedBoucherS** [comment]
Hello,
try setting the _SelectAllContent_ property to something else.
Thank you

**Comment by RejeanLabbe** [comment]
@XceedBoucherS The **_SelectAllContent_** property works for the top item of the list, but the text **_All_** is shown if all items are selected. Is there a property to change it?

![image](https://github.com/xceedsoftware/wpftoolkit/assets/5299301/59279158-ee2b-4387-8e21-b185193256ea)


Thanks

**Comment by XceedBoucherS** [comment]
Hi,

Sorry for the delay, I was on vacations.
Try with the "AllItemsSelectedContent" property.

Thank you

**Comment by RejeanLabbe** [comment]
@XceedBoucherS Excellent! It's exactly what I was looking for.

Thanks!
