### ISSUE TITLE
PropertyGrid's CategoryOrder is ignored when CategoryPropertyOrder is set to Declaration

### ISSUE THREAD

**Issue by e23099** [xceedsoftware/wpftoolkit#1728]
As the title suggest, I want to use the declaration order for the properties in each Category, but still want the category be ordered by the 
specified category order, since derived class may make the declaration order a mess.

An example is like the following code.
```
[CategoryPropertyOrder(CategoryPropertyOrderEnum.Declaration)]
[CategoryOrder("AAA", 1)]
[CategoryOrder("BBB", 2)]
public class BaseClass
{
    [Category("AAA")]
    public string version { get; set; }
}

public class DerivedClass : BaseClass
{
    [Category("BBB")]
    public string PropertyB2 {get;set;}

    [Category("BBB")]
    public string PropertyB1 {get;set;}
}
```

The result is when I set a PropertyGrid's SelectedObject to a DerivedClass instance, the PropertyGrid shows:
* BBB
    * PropertyB2
    * PropertyB1
* AAA
    * version

However what I expect is:
* AAA
    * version
* BBB
    * PropertyB2
    * PropertyB1

It seems like the `CategoryOrder` is not preserved anymore when `CategoryPropertyOrderEnum.Declaration` is applied.
I didn't dig in to the code, not sure if there is other clean solution to this problem.

**Comment by XceedBoucherS** [comment]
Hi,

Can you go in file: Xceed.Wpf.Toolkit/PropertyGrid/Implementation/PropertyItemCollection.cs,
In method: UpdateCategorization
And remove the condition : if( sortAlphabetically ), located inside the condition : if( groupDescription != null )

With this change, using:
 [CategoryPropertyOrder( CategoryPropertyOrderEnum.Declaration )]
  [CategoryOrder( "AAA", 1 )]
  [CategoryOrder( "BBB", 2 )]
will make sure Category AAA will be displayed before Category BBB and the properties inside Category BBB (and AAA) will use the declaration order.

Thankyou for pointing this out.

**Comment by e23099** [comment]
That works, thanks.
