### ISSUE TITLE
PropertyGrid is empty despite giving extra content

### ISSUE THREAD

**Issue by TracerDS** [xceedsoftware/wpftoolkit#1737]
Hi. As the title suggests the PropertyGrid is totally empty.
Code:
```xml
...
<xctk:PropertyGrid x:Name="_propertyGrid" AutoGenerateProperties="False">
    <xctk:PropertyGrid.PropertyDefinitions>
        <xctk:PropertyDefinition TargetProperties="FirstName" />
        <xctk:PropertyDefinition TargetProperties="FavoriteColor" />
        <xctk:PropertyDefinition TargetProperties="PetNames" />
    </xctk:PropertyGrid.PropertyDefinitions>
</xctk:PropertyGrid>
...
```
![image](https://user-images.githubusercontent.com/43095317/214097823-94553b58-955d-4f0d-b785-2c42780df290.png)
No errors, package was included in references and added to xml.
Did I do something wrong? 🤔

**Comment by XceedBoucherS** [comment]
Hi
You must specify a SelectedObject for the PropertyGrid to display the properties of the object.
Also, if you set the PropertyDefinitions of the PropertyGrid, only the properties FirstName, FavoriteColor and PetNames should be displayed....but the PropertyGrid's SelectedObject must contain these properties or else, nothing will be shown.

Thank you.
