### ISSUE TITLE
The tag 'DataGridControl' does not exist in XML namespace

### ISSUE THREAD

**Issue by selectmarketingllc** [xceedsoftware/wpftoolkit#1747]
I am migrating a .NET Framework 4.61 WPF application to .NET 7.  The original application is using Extended.Wpf.Toolkit 3.4.0.  The new application is using 4.5.0.  I copied the XAML from one application to the other, including the namespace.

xmlns:xcdg="http://schemas.xceed.com/wpf/xaml/datagrid"

<xcdg:DataGridControl ....>
</xcdg:DataGridControl>

However, I get an error that DataGridControl does not exist in the namespace.

MC3074	The tag 'DataGridControl' does not exist in XML namespace 'http://schemas.xceed.com/wpf/xaml/datagrid'. Line 48 Position 22.

**Comment by XceedBoucherS** [comment]
Hi @selectmarketingllc ,
Starting at v3.5, the Toolkit no longer include the DataGrid control:
https://github.com/xceedsoftware/wpftoolkit/wiki/Improvements-in-v3.5.0

Please note that this is a big control which is now available in the Plus version of the Toolkit. It`s the only control who had this type of conversion in the Toolkit. 

You can try the Plus version of the Toolkit here: https://xceed.com/en/our-products/product/toolkit-plus-for-wpf
If you want to try the Full DataGrid control(with even more features than the Toolkit`s DataGrid), you can try it here: https://xceed.com/en/our-products/product/datagrid-for-wpf

Thanks.
