### ISSUE TITLE
[Suggest] TimeSpanUpDown With Hours >= 24

### ISSUE THREAD

**Issue by tqk2811** [xceedsoftware/wpftoolkit#1757]
Default: `1.12:32:21` is 1 day, 12 hours, ....
I want a flag to show as `36:32:21`

**Comment by XceedBoucherS** [comment]
Hi,

Have you tried setting the TimeSpanUpDown.ShowDays property to false ?

Thank you

**Comment by zhongruijia** [comment]
这里是郭瑞的邮箱，已收到您的来件，我会尽快拜阅并给予您回复

**Comment by tqk2811** [comment]
> ShowDays

oh it work, thanks
