### ISSUE TITLE
DateTimePicker - wrong values in time picker dropdown part

### ISSUE THREAD

**Issue by kuceraz** [xceedsoftware/wpftoolkit#1774]
Starting at version 4.4.0, there are no longer time intervals to select in time picker part, but "menu text" items, which does nothing.
4.3.0 is the last properly working version
It can be seen in the following screenshot.
![obrazek](https://github.com/xceedsoftware/wpftoolkit/assets/162991446/e8f6e1aa-3a40-4037-b68f-fa74ae8f2bd0)

**Comment by XceedBoucherS** [comment]
Hi,

I just tried the latest version available on NuGet, v4.6. I created a new project and added a DateTimePicker:
![image](https://github.com/xceedsoftware/wpftoolkit/assets/29377763/85c3304a-2caa-4408-8340-b6a34300b3fd)

Here's the result:
![image](https://github.com/xceedsoftware/wpftoolkit/assets/29377763/a346e8f5-9e9a-42e5-825d-cbec87ecc8af)

Could you submit your code ?
Thanks

**Comment by kuceraz** [comment]
Hi, I have tried to create minimum example to reproduce this error and finally it seems to be problem on my side.
Specifically it is caused by some styles which manipulate with ListBoxItems.
It is quite weird that older versions of DateTimePicker work good, but it seems that wpftoolkit is not the problem after all, so I think we can close this issue.
