### ISSUE TITLE
The invocation of the constructor on type 'Xceed.Wpf.DataGrid.DataGridControl' that matches the specified binding constraints threw an exception.

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#775]
<b>justin0805[CodePlex]</b> <br />I added the xceed.wfp.Datagrid assembly reference dll. After which i added the DataGrid in my XAML. when i try to run i get the following error.

Did any one run into this issue. Iquotm running .net framework 4 VS 2010. Could someone tell me what am i doing wrong?

**Comment by xceedsoftware** [comment]
<b>justin0805[CodePlex]</b> <br />I found the soulution. I was using runtime version v2.0.50727. I removed that reference and added a new reference that had runtime version v4.0.30319 and it worked.

**Comment by IAMShashankk** [comment]
Hi,

I am also getting the same exception and using v2.0.50727. I can not change runtime version currently.
Could you please help what I can do to avoid this exception.
