### ISSUE TITLE
DateTimePicker crash if value is smaller than MinValue

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#858]
<b>toka_[CodePlex]</b> <br />DateTimePicker crash if value is smaller than MinValue

How to reproduce crash in LiveExplorer:

Select current date in DateTimePicker. Set minimum value to tomorrow.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

You can use your own DateTimePicker and override the OnCoerceMinimum to react before the throw will happen :
 public class MyDateTimePicker : DateTimePicker
  {
    protected override System.DateTime? OnCoerceMinimum( System.DateTime? baseValue )
    {
      if( baseValue  this.Value )
      {
        System.Diagnostics.Debug.WriteLine(Minimum is greater than selected date...it will throw.);
      }
      return base.OnCoerceMinimum( baseValue );
    }
  }

**Comment by xceedsoftware** [comment]
<b>hanns_echtleder[CodePlex]</b> <br />I can understand that this raises an exception. But how can I handle it? 

In my application I have a view model that has DateTime values bound to Value, Minimum and Maximum of the DateTimePicker. Now when data is loaded where the selected value isn't in min-max range (for whatever reason) the whole application crashes due to the
 exception thrown in OnApplyTemplate of the DateTimePicker. 

I have found no way to handle that error yet (except of course check dates in the view model, which would require me to change a lot of existing code instead of having one generic error handling in the view level), and I think the control should be a bit more
 robust.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This is a normal ArgumentOutOfRangeException since the current Value is now included in Blackout dates.


http://msdn.microsoft.com/en-us/library/system.windows.controls.datepicker.selecteddate(v=vs.110).aspx

**Comment by thirking** [comment]
The problem is ：

> `private void SetBlackOutDates()
    {
      if( _calendar != null )
      {
        _calendar.BlackoutDates.Clear();

        if( ( this.Minimum != null ) && this.Minimum.HasValue && ( this.Minimum.Value != DateTime.MinValue ) )
        {
          DateTime minDate = this.Minimum.Value;
          _calendar.BlackoutDates.Add( new CalendarDateRange( DateTime.MinValue, minDate.AddDays( -1 ) ) );
        }
        if( ( this.Maximum != null ) && this.Maximum.HasValue && ( this.Maximum.Value != DateTime.MaxValue ) )
        {
          DateTime maxDate = this.Maximum.Value;
          _calendar.BlackoutDates.Add( new CalendarDateRange( maxDate.AddDays( 1 ), DateTime.MaxValue ) );
        }
      }
    }`

if I set `Maximum` as DateTime.MaxValue, maxDate.AddDays(1) will throw an exception, `Minimum` is the same .

**Comment by XceedBoucherS** [comment]
Hi,

Thank you for reporting this. It will be fixed in v3.9.
