### ISSUE TITLE
Set current DateTime Part

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#967]
<b>BoucherS[CodePlex]</b> <br />a user ask :

Hi, how can I set default increment /decrement fields of TimeSpan other than hours, for example minutes or seconds.

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 

This will be fixed in v2.9. 
The new Property CurrentDateTimePart will let you set the DateTimePart that will be modified when using the Up/Down buttons or Up/Down keys.

**Comment by iberisoft** [comment]
I use `CurrentDateTimePart="Second"` under Extended.Wpf.Toolkit v4.0.1 however the spin buttons increment/decrement the hour part.

**Comment by XceedBoucherS** [comment]
Hi iberisoft,
This will be fixed in v4.1.
It only happens when the TimeSpanUpDown do not have a Value. If you set a Value, the CurrentDateTimePart will work.
Thank you
